smartrent/grizzly

- lib/grizzly.ex
Still, need to test on hardware, just wanted to get the code under review.
> Allow send_command to take node_id

- lib/grizzly/command/encoding.ex
- lib/grizzly/command_class/association/set.ex
- lib/grizzly/command_class/switch_binary/set.ex
- test/grizzly/command_class/association/set_test.exs
- test/grizzly/command_class/switch_binary/set_test.exs
> Encode errors for cc Association

- lib/grizzly/command/encoding.ex
- lib/grizzly/command_class/configuration/bulk_get.ex
- lib/grizzly/command_class/network_management_inclusion.ex
- lib/grizzly/command_class/network_management_inclusion/node_add.ex
- lib/grizzly/command_class/network_management_inclusion/node_add_dsk_set.ex
- lib/grizzly/command_class/network_management_inclusion/node_add_keys_set.ex
- lib/grizzly/command_class/network_management_inclusion/node_neighbor_update_request.ex
- lib/grizzly/command_class/network_management_inclusion/node_remove.ex
- test/grizzly/command_class/network_management_inclusion/node_add_dsk_set_test.exs
- test/grizzly/command_class/network_management_inclusion/node_add_keys_set_test.exs
- test/grizzly/command_class/network_management_inclusion/node_neighbor_update_request_test.exs
- test/grizzly/command_class/network_management_inclusion_test.exs
> Encode errors for cc NetworkManagementInclusion

- lib/grizzly/command_class/network_management_proxy/node_info_cache.ex
- test/grizzly/command_class/network_management_proxy/node_info_cache_test.exs
> Encodes errors for cc NetworkManagementProxy.

- lib/grizzly/command_class/network_management_installation_maintenance/priority_route_get.ex
- lib/grizzly/command_class/network_management_installation_maintenance/statistics_clear.ex
- lib/grizzly/command_class/network_management_installation_maintenance/statistics_get.ex
- test/grizzly/command_class/network_management_installation_maintenance/priority_route_get_test.exs
- test/grizzly/command_class/network_management_installation_maintenance/statistics_clear_test.exs
- test/grizzly/command_class/network_management_installation_maintenance/statistics_get_test.exs
> Encodes errors for cc NetworkManagementInstallationMaintenance.

- lib/grizzly/command_class/powerlevel.ex
- lib/grizzly/command_class/powerlevel/set.ex
- lib/grizzly/command_class/powerlevel/test_node_set.ex
- test/grizzly/command_class/powerlevel/set_test.exs
- test/grizzly/command_class/powerlevel/test_node_set_test.exs
> Encodes errors for cc Powerlevel.

- lib/grizzly/command/encoding.ex
- lib/grizzly/command_class/schedule_entry_lock.ex
- lib/grizzly/command_class/schedule_entry_lock/daily_repeating_get.ex
- lib/grizzly/command_class/schedule_entry_lock/daily_repeating_set.ex
- lib/grizzly/command_class/schedule_entry_lock/enable_all_set.ex
- lib/grizzly/command_class/schedule_entry_lock/enable_set.ex
- lib/grizzly/command_class/schedule_entry_lock/year_day_get.ex
- lib/grizzly/command_class/schedule_entry_lock/year_day_set.ex
- test/grizzly/command_class/schedule_entry_lock/daily_repeating_get_test.exs
- test/grizzly/command_class/schedule_entry_lock/daily_repeating_set_test.exs
- test/grizzly/command_class/schedule_entry_lock/enable_set_test.exs
- test/grizzly/command_class/schedule_entry_lock/year_day_get_test.exs
- test/grizzly/command_class/schedule_entry_lock/year_day_set_test.exs
- test/grizzly/packet/body_parser_test.exs
> Encodes errors for cc ScheduleEntryLock.

- lib/grizzly/command_class/thermostat_mode.ex
- lib/grizzly/command_class/thermostat_mode/set.ex
- lib/grizzly/packet/body_parser.ex
- test/grizzly/command_class/thermostat_mode/set_test.exs
- test/grizzly/command_class/thermostat_mode_test.exs
> Encodes errors for cc ThermostatMode.

- lib/grizzly/command_class/thermostat_fan_mode.ex
- lib/grizzly/command_class/thermostat_fan_mode/set.ex
- test/grizzly/command_class/thermostat_fan_mode/set_test.exs
- test/grizzly/command_class/thermostat_fan_mode_test.exs
> Encodes errors for cc ThermostatFanMode.

- lib/grizzly/command_class/switch_multilevel.ex
- lib/grizzly/command_class/switch_multilevel/set.ex
- test/grizzly/command_class/switch_multilevel/get_test.exs
- test/grizzly/command_class/switch_multilevel/set_test.exs
> Encodes errors for cc SwitchMultilevel.

- lib/grizzly/command_class/multilevel_sensor.ex
- lib/grizzly/command_class/sensor_multilevel/get.ex
- test/grizzly/command_class/sensor_multilevel/get_test.exs
> Encodes errors for cc SensorMultilevel.

- lib/grizzly/command_class/wake_up/no_more_information.ex
- mix.exs
- test/grizzly/command_class/wake_up/no_more_information_test.exs
> Support for WakeUp CC's NoMoreInformation command

- lib/grizzly.ex
- lib/grizzly/command_class/zwaveplus_info.ex
- lib/grizzly/command_class/zwaveplus_info/get.ex
- lib/grizzly/packet/body_parser.ex
- mix.exs
- test/grizzly/command_class/zwaveplus_info/get_test.exs
- test/grizzly/packet/body_parser_test.exs
> Supports ZwaveplusInfo command class

- lib/grizzly/command_class/wake_up/interval_get.ex
- lib/grizzly/packet/body_parser.ex
- test/grizzly/command_class/wake_up/interval_get_test.exs
- test/grizzly/packet/body_parser_test.exs
> Fixes to getting manufacturer info and wake-up interval

- lib/grizzly/command/encoding.ex
- lib/grizzly/command_class/user_code.ex
- lib/grizzly/command_class/user_code/get.ex
- lib/grizzly/command_class/user_code/set.ex
- test/grizzly/command_class/user_code/get_test.exs
- test/grizzly/command_class/user_code/set_test.exs
- test/grizzly/command_class/user_codes_test.exs
> Handle (re)setting user codes correctly.

- lib/grizzly/command/encoding.ex
- lib/grizzly/command_class/user_code.ex
- lib/grizzly/command_class/user_code/get.ex
- lib/grizzly/command_class/user_code/set.ex
- test/grizzly/command_class/user_code/get_test.exs
- test/grizzly/command_class/user_code/set_test.exs
- test/grizzly/command_class/user_codes_test.exs
> Handle setting user codes correctly.

- lib/grizzly/command_class/network_management_inclusion.ex
- lib/grizzly/command_class/network_management_inclusion/failed_node_remove.ex
- lib/grizzly/packet/body_parser.ex
- test/grizzly/command_class/network_management_inclusion/failed_node_remove_test.exs
- test/grizzly/packet/body_parser_test.exs
> Support removing failed nodes.

- README.md
- config/config.exs
- lib/grizzly/application.ex
This has the configuration for zipgateway, check for the kext, and some updates to the README to explain what's going on.
> start making stuff configurable

- example/lib/example.ex
- lib/grizzly/application.ex
This pulls out the clean up from #100
> Clean up formatting and example

- lib/grizzly/command_class/zip_nd/inv_node_solicitation.ex
- lib/grizzly/network.ex
- lib/grizzly/node.ex
- lib/grizzly/packet/decode.ex
- test/grizzly/command_class/zip_nd/inv_node_solicitation_test.exs
- test/grizzly/packet/decode_test.exs
- test/grizzly_test.exs
> Add home_id to the node struct

- lib/grizzly/command_class/node_provisioning/list_iteration_get.ex
- lib/grizzly/packet/body_parser.ex
- mix.exs
- test/grizzly/command_class/node_provisioning/list_iteration_get_test.exs
- test/grizzly/packet/body_parser_test.exs
> Node provisioning list iteration get command

- lib/grizzly/command_class/node_provisioning/delete.ex
- mix.exs
- test/grizzly/command_class/node_provisioning/delete_test.exs
> NodeProvisioning Delete command

- lib/grizzly/command_class/node_provisioning/list_all.ex
- lib/grizzly/packet/body_parser.ex
- mix.exs
- test/grizzly/command_class/node_provisioning/list_all_test.exs
> Add NodeProvisioning ListAll command

- lib/grizzly/command_class/time/offset_set.ex
> Set correct constraints on Time offset_set parameters

- lib/grizzly/conn/server.ex
Potentially fixes #65
This may be a simple solution, but I also may not properly understand how everything works yet.
We could also update this to schedule the next heartbeat for the **timer config minus the current time that's passed** to make it more accurate. For example, if the timer is set for **25 seconds** and the `last_command_at` was **15 seconds** ago, we don't want to send a heartbeat yet, but we may want to schedule it for (the difference of) **10 seconds** from now. _(edit: done in 5caa821)_
> Keep track of last command time (for heartbeats)

- README.md
- lib/grizzly.ex
- lib/grizzly/notifications.ex
Added some documentation about Notification subscriptions.
Feel free to tweak or completely replace as needed, I won't be offended, I just thought something is better than nothing.
> Add notifications docs

- lib/grizzly/command_class/multi_channel_association/set.ex
- lib/grizzly/command_class/wake_up/interval_capabilities_get.ex
- lib/grizzly/packet/body_parser.ex
- test/grizzly/command_class/multi_channel_association/set_test.exs
Fixes SRHUB-187
Per certification review
> Support Wake Up v2 and Multi Channel Association v3

- lib/grizzly.ex
- lib/grizzly/command_class/door_lock.ex
- lib/grizzly/command_class/multi_channel_association.ex
- lib/grizzly/command_class/network_management_basic.ex
- lib/grizzly/command_class/network_management_inclusion/node_add.ex
- lib/grizzly/command_class/network_management_inclusion/node_remove.ex
- lib/grizzly/command_class/thermostat_setback.ex
- lib/grizzly/command_class/version.ex
- lib/grizzly/command_class/zwaveplus_info.ex
- lib/grizzly/controller.ex
- lib/grizzly/inclusion.ex
- lib/grizzly/network.ex
- lib/grizzly/notifications.ex
- lib/grizzly/packet.ex
- lib/grizzly/security.ex
- lib/grizzly/smart_start/meta_extension/product_id.ex
Even though underspecs is off, several of these looked like copy/paste or
accidental errors that would be nice to fix.
> Fix Dialyzer underspecs

- lib/grizzly.ex
> Fix spec from reset_controller

- lib/grizzly.ex
- lib/grizzly/conn.ex
- lib/grizzly/conn/server.ex
by adding {:ok, :queued, reference} as alternate returned value
> Fix spec for send_command

- lib/grizzly/commands/table.ex
> Better table lookup error message

- lib/grizzly/zwave/dsk.ex
Z-Wave is very picky on the DSK, so let Dialyzer know that.
> Tighten DSK spec

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/command_classes/sensor_binary.ex
- lib/grizzly/zwave/commands/sensor_binary_get.ex
- lib/grizzly/zwave/commands/sensor_binary_report.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/sensor_binary_get_test.exs
- test/grizzly/zwave/commands/sensor_binary_report_test.exs
> Sensor Binary CC

- lib/grizzly/connection.ex
- lib/grizzly/connections.ex
- lib/grizzly/connections/supervisor.ex
- lib/grizzly/connections/sync_connection.ex
- lib/grizzly/network.ex
- test/grizzly/connection_test.exs
> Fix unclosed connections on controller reset

- lib/grizzly/commands/table.ex
> get configuration fix

- lib/grizzly/zwave/command_classes/sensor_multilevel.ex
- test/grizzly/zwave/commands/sensor_multilevel_supported_sensor_report_test.exs
The encoding and decoding was not correct.
> Fixed supported sensors report

- lib/grizzly/zwave/command_classes/hail.ex
- lib/grizzly/zwave/commands/hail.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/hail_test.exs
> Support handling Hail command

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/command_classes/indicator.ex
- lib/grizzly/zwave/commands/indicator_description_get.ex
- lib/grizzly/zwave/commands/indicator_description_report.ex
- lib/grizzly/zwave/commands/indicator_get.ex
- lib/grizzly/zwave/commands/indicator_report.ex
- lib/grizzly/zwave/commands/indicator_set.ex
- lib/grizzly/zwave/commands/indicator_supported_get.ex
- lib/grizzly/zwave/commands/indicator_supported_report.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/indicator_description_get_test.exs
- test/grizzly/zwave/commands/indicator_description_report_test.exs
- test/grizzly/zwave/commands/indicator_get_test.exs
- test/grizzly/zwave/commands/indicator_report_test.exs
- test/grizzly/zwave/commands/indicator_set_test.exs
- test/grizzly/zwave/commands/indicator_supported_get_test.exs
- test/grizzly/zwave/commands/indicator_supported_report_test.exs
Needed for ZWave Plus v2 certification
> SRHUB 281 - Indicator CC

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/command_classes/antitheft.ex
- lib/grizzly/zwave/commands/antitheft_get.ex
- lib/grizzly/zwave/commands/antitheft_report.ex
- lib/grizzly/zwave/commands/antitheft_set.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/antitheft_get_test.exs
- test/grizzly/zwave/commands/antitheft_report_test.exs
- test/grizzly/zwave/commands/antitheft_set_test.exs
> SRHUB 282 - Antitheft CC

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/command_classes.ex
- lib/grizzly/zwave/command_classes/antitheft_unlock.ex
- lib/grizzly/zwave/commands/antitheft_unlock_get.ex
- lib/grizzly/zwave/commands/antitheft_unlock_report.ex
- lib/grizzly/zwave/commands/antitheft_unlock_set.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/antitheft_unlock_get_test.exs
- test/grizzly/zwave/commands/antitheft_unlock_report_test.exs
- test/grizzly/zwave/commands/antitheft_unlock_set_test.exs
> SRHUB 283 - Antitheft Unlock CC

- lib/grizzly/connections/sync_connection.ex
- test/support/server.ex
There are two different times we can get an `:ack_request`
1. When the `zigpateway` server sends one to ping the client
2. When the `zipgateway` server wants to ensure packet delivery to the
client.
Grizzly only handled the first one. With `zigpateway` 7.14 it appears it
sends `:ack_request` on all packets so this fix should account for the
second reason `Grizzly` might receive an `:ack_request` as part of the
Z/IP packet with a command report.
> Fix ack request handling

- lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
- lib/grizzly/zwave/crc.ex
- lib/grizzly/zwave/crc/table.ex
- mix.exs
- mix.lock
- test/grizzly/zwave/crc_test.exs
> Remove CRC package, use internal CRC module

- lib/grizzly/command_handlers/aggregate_report.ex
- test/grizzly/command_handlers/aggregate_report_test.exs
Also provides fixes and tests around proper aggregation of reports.
closes: #330
> Fix aggregate reports failing on non-expected commands

- lib/grizzly/unsolicited_server/response_handler.ex
We generalized sending and `:ack_response` to an unsolicited
notification when the unsolicited server is only supposed to
receive commands and not send as per the `zipgateway` documentation.
This removes doing that and tries to handle a supported extra command if
we cannot handle the extra command we assume that it is a notification
and we broadcast that to whoever is registered to list for that
notification.
> Remove sending ack response to unsolicited notifications

- lib/grizzly/unsolicited_server/response_handler.ex
Support when a notification is encapsulated in a `SupervisionGet`
command.
We have to inspect the inner encapsulated command and decode it. Then we
can pass back the command for the `handle_response/3` function can use
the decoded inner command for broadcasting to all the registered
listeners.
If we are unable to decode it, we will just log a warning for now as the
main mechanism for subscribing to unsolicited reports does not support
listening from binary representations yet.
> Support SupervisionGet encapsulated notifications

- lib/grizzly/zwave/notifications.ex
> Add support for access control unknown event notification

- lib/grizzly/associations.ex
- lib/grizzly/options.ex
- lib/grizzly/supervisor.ex
- lib/grizzly/unsolicited_server.ex
- lib/grizzly/unsolicited_server/response_handler.ex
- lib/grizzly/unsolicited_server/socket.ex
- lib/grizzly/unsolicited_server/socket_supervisor.ex
- test/grizzly/associations_test.exs
There are some logical requirements that needed to be fulfilled around
associations and the existing code did not seem handle the cases very
well. Moreover, there was a strong coupling of the file writing and
reading code with the command processing code. I pulled the coupling
apart a bit more to allow for better testing and separation of logical
units of work.
> Refactor Associations Persistence

- lib/grizzly/unsolicited_server/messages.ex
Sometimes, what's being broadcast is not a ZIPPacket command but a "straight" command
> SRHUB 341 - Some unsolicited reports were not sent

- CHANGELOG.md
- README.md
- mix.exs
> Revert "v0.15.6"

- lib/grizzly/node.ex
When getting a node information `zipgateway` will use a cache to try to
minimize the Z-Wave traffic. However, sometimes it will hold on to the
cached information about a device for too long.
This allows forcing the cache to update when requesting the node
information.
> Add support for updating node information cache

- lib/grizzly/zwave/commands/s2_resynchronization_event.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/s2_resynchronization_event_test.exs
> Add S2ResynchronizationEvent

- lib/grizzly/unsolicited_server/response_handler.ex
When a command is sent via supervision get we were not processing that
command internally. With supervision get commands we have to send the
supervision report last after doing any actions that are needed based
on the encapsulated command.
Supervision get commands only encapsulate set type of commands that do
have a report to follow. Due to this Grizzly does not need to worry
about encapsulating commands in supervision at this level as of right
now.
> Process supervision encapsulated command

- lib/grizzly/zwave/commands/firmware_md_report.ex
- lib/grizzly/zwave/commands/version_report.ex
- test/grizzly/zwave/commands/firmware_md_report_test.exs
- test/grizzly/zwave/commands/version_report_test.exs
and patch for version_report v3
> firmware_md_report v5 patch for zg 7.14.2

- lib/grizzly/zwave/dsk.ex
- lib/grizzly/zwave/qr_code.ex
- test/grizzly/zwave/qr_code_test.exs
This adds support for generating QR Codes for smart start and S2
devices.
> Add QR code generation support

- lib/grizzly/zwave/commands/failed_node_remove.ex
- lib/grizzly/zwave/commands/failed_node_remove_status.ex
- lib/grizzly/zwave/commands/node_remove_status.ex
- test/grizzly/zwave/commands/failed_node_remove_status_test.exs
- test/grizzly/zwave/commands/failed_node_remove_test.exs
Adds support the updates needed for our existing command classes to
parse 16 bit node ids.
closes: #473
> Support long range NetworkManagementInclusion command class

- lib/grizzly/zwave/command.ex
- lib/grizzly/zwave/commands/node_remove_status.ex
- test/grizzly/zwave/commands/node_remove_status_test.exs
- Add `encode_params/2` callback
- Support v4 of NodeRemoveStatus command
> node remove status extended node ids

- lib/grizzly/zwave/commands/failed_node_remove_status.ex
- test/grizzly/zwave/commands/failed_node_remove_status_test.exs
> Support version 4 FailedNodeRemoveStatus

- lib/grizzly/zwave/commands/node_info_cached_get.ex
- test/grizzly/zwave/commands/node_info_cached_get_test.exs
> Support v4 NodeInfoCachedGet

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/commands/zwave_long_range_channel_get.ex
- lib/grizzly/zwave/commands/zwave_long_range_channel_report.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/zwave_long_range_channel_get_test.exs
- test/grizzly/zwave/commands/zwave_long_range_channel_report_test.exs
- Add ZWaveLongRangeChannelGet command
- Add `ZWaveLongRangeChannelReport` command
- send long range channel get command
> lr channel get report

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/command_classes/network_management_inclusion.ex
- lib/grizzly/zwave/commands/failed_node_remove.ex
- lib/grizzly/zwave/commands/failed_node_remove_status.ex
- lib/grizzly/zwave/commands/network_management_multi_channel_end_point_get.ex
- lib/grizzly/zwave/commands/network_management_multi_channel_end_point_report.ex
- lib/grizzly/zwave/commands/node_info_cached_get.ex
- lib/grizzly/zwave/commands/node_remove_status.ex
- lib/grizzly/zwave/decoder.ex
- lib/grizzly/zwave/node_id.ex
- test/grizzly/zwave/command_classes/network_management_inclusion_test.exs
- test/grizzly/zwave/commands/failed_node_remove_status_test.exs
- test/grizzly/zwave/commands/failed_node_remove_test.exs
- test/grizzly/zwave/commands/network_management_multi_channel_end_point_get_test.exs
- test/grizzly/zwave/commands/network_management_multi_channel_end_point_report_test.exs
- test/grizzly/zwave/commands/node_info_cached_get_test.exs
- test/grizzly/zwave/commands/node_remove_status_test.exs
- test/grizzly/zwave/node_id_test.exs
- Add NodeId helper module
- Add NetworkManagementMultiChannelEndPointGet command
- Add NetworkManagementMultiChannelEndPointReport command
Closes: #484
Closes: #485
> nw mutli channel end point get report

- lib/grizzly/zwave/commands/version_report.ex
Support the latest zipgateway release and ruggedize the fallback parameter decoding
> Version report fix

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/command_classes.ex
- lib/grizzly/zwave/commands/network_management_multi_channel_capability_get.ex
- lib/grizzly/zwave/commands/network_management_multi_channel_capability_report.ex
- lib/grizzly/zwave/decoder.ex
- lib/grizzly/zwave/node_id.ex
- test/grizzly/zwave/commands/network_management_multi_channel_capability_get_test.exs
- test/grizzly/zwave/commands/network_management_multi_channel_capability_report_test.exs
- test/grizzly/zwave/node_id_test.exs
- Add NetworkManagementMultiChannelCapabilityGet
- Add NetworkManagementMultiChannelCapabilityReport
Closes: #486
Closes: #487
> nw multi channel capability get report

- lib/grizzly/commands/command.ex
- lib/grizzly/zwave/commands/zip_packet/header_extensions/installation_and_maintenance_report.ex
- test/grizzly/commands/command_test.exs
- Parse new IME tx stats
- Filter new transmission stats
> zip command class v5

- lib/grizzly/options.ex
- lib/grizzly/status_reporter/console.ex
- lib/grizzly/supervisor.ex
- lib/grizzly/zipgateway/ready_checker.ex
- test/grizzly/connection_test.exs
- Status reporter behaviour
- Refactor the on_ready function to use the new StatusReporter
Depends on #603
> on ready to reporter refactor

- README.md
- lib/grizzly/firmware_error.ex
- lib/grizzly/options.ex
- lib/grizzly/status_reporter.ex
- lib/grizzly/supervisor.ex
- lib/grizzly/zipgateway/ready_checker.ex
- lib/grizzly/zwave_firmware.ex
See https://github.com/smartrent/smartrent_hub/pull/187
> Firmware update on start

- lib/grizzly/zwave/notifications.ex
> Unknown user code expressed as empty string

- mix.exs
> Removed race_conditions dialyzer flag

- lib/grizzly/node.ex
This provides better support for force a cache update when getting node
information and provides a shorter default time to refresh the cache.
Sometimes, refreshing a device's information in the cache takes more
time to complete, so this increases the timeout value to 10 seconds
rather than the default 5 seconds. If the information is cached and
there is no force update or the max age of the record is still okay the
information returns immediately and the increased timeout has no effect.
> Fix get_info/2 to allow forcing a cache update

- lib/grizzly/virtual_devices/temperature_sensor.ex
- lib/grizzly/virtual_devices/thermostat.ex
Else one can not set the inclusion handler option
> Don't ignore virtual device options on start

- lib/grizzly/zwave/commands/association_group_name_report.ex
- lib/grizzly/zwave/commands/manufacturer_specific_device_specific_report.ex
- lib/grizzly/zwave/commands/switch_multilevel_start_level_change.ex
- lib/grizzly/zwave/commands/version_report.ex
- lib/grizzly/zwave/qr_code.ex
The Elixir 1.13 formatter causes new format warnings
> Reformat for Elixir 1.13

- CHANGELOG.md
- mix.exs
- Added un-grouped modules to groups
- Enable nesting by prefix for command classes and commands for readability
- Fixes some CLI warnings emitted when generating docs
> Improve docs organization

- lib/grizzly/zwave/command_classes.ex
- lib/grizzly/zwave/device_classes.ex
Ensures types always stay in sync with mappings.
> Generate types for command classes and device classes

- lib/grizzly/zwave/commands/switch_multilevel_report.ex
- test/grizzly/zwave/commands/switch_multilevel_report_test.exs
> Multilevel switch level 0xFF is now 100 not 99

- example/lib/example.ex
- lib/grizzly/virtual_devices/thermostat.ex
- lib/grizzly/zwave/command_classes/thermostat_setpoint.ex
- test/grizzly/virtual_devices/thermostat_test.exs
- test/grizzly/zwave/commands/thermostat_setpoint_report_test.exs
- test/grizzly/zwave/commands/thermostat_setpoint_set_test.exs
- test/test_helper.exs
Closes #704.
**BREAKING CHANGE**
> Use abbreviations for temperature scales

- dialyzer_ignore_warnings.exs
- lib/grizzly/command_handlers/aggregate_report.ex
- lib/grizzly/commands.ex
- lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
- lib/grizzly/inclusions.ex
- lib/grizzly/trace/record_queue.ex
- lib/grizzly/virtual_devices.ex
- lib/grizzly/zipgateway/config.ex
- lib/grizzly/zwave/commands/barrier_operator_signal_report.ex
- lib/grizzly/zwave/commands/barrier_operator_signal_set.ex
- lib/grizzly/zwave/commands/door_lock_operation_report.ex
- lib/grizzly/zwave/commands/failed_node_remove_status.ex
- lib/grizzly/zwave/commands/powerlevel_report.ex
- lib/grizzly/zwave/commands/powerlevel_set.ex
- lib/grizzly/zwave/commands/powerlevel_test_node_report.ex
- lib/grizzly/zwave/commands/powerlevel_test_node_set.ex
- lib/grizzly/zwave/commands/thermostat_setpoint_supported_report.ex
- lib/grizzly/zwave/commands/window_covering_stop_level_change.ex
- lib/grizzly/zwave/decode_error.ex
- mix.exs
- Enable and fix Dialyzer `:missing_return`
- Enable and fix Dialyzer `:extra_return`
> Enable and fix Dialyzer extra/missing return options

- lib/grizzly/zwave/commands/switch_multilevel_report.ex
- lib/grizzly/zwave/commands/switch_multilevel_set.ex
- test/grizzly/zwave/commands/switch_multilevel_report_test.exs
> Multilevel switch level of 99 means 100% hardware level

- lib/grizzly/commands/table.ex
- lib/grizzly/network.ex
- lib/grizzly/zwave/commands/node_neighbor_update_request.ex
- lib/grizzly/zwave/commands/node_neighbor_update_status.ex
- lib/grizzly/zwave/commands/version_capabilities_get.ex
- lib/grizzly/zwave/commands/version_capabilities_report.ex
- lib/grizzly/zwave/commands/version_zwave_software_get.ex
- lib/grizzly/zwave/commands/version_zwave_software_report.ex
- lib/grizzly/zwave/decoder.ex
- lib/grizzly/zwave/device_classes.ex
* Network Management Inclusion CC
* Node Neighbor Update Request
* Node Neighbor Update Status
* Version CC
* Version Capabilities Get/Report
* Version Z-Wave Software Get/Report
> Implement additional debugging and network maintenance commands

- lib/grizzly/trace/record.ex
> Fix trace dump for :no_operation commands

- lib/grizzly/zwave/command_classes/network_management_installation_maintenance.ex
- lib/grizzly/zwave/commands/rssi_report.ex
- test/grizzly/zwave/commands/rssi_report_test.exs
As it turns out, Z/IP Gateway will send whatever RSSI value it actually
measures rather than just what's in the spec. This means that -10dBm is
valid even though the spec says only -32..-128. When Grizzly received an
out-of-spec value for LR channels, it would return a DecodeError.
Out-of-spec values for non-LR channels would be silently dropped, which
is not desirable behavior (since you have no way to know what channel(s)
any remaining values belong to).
Instead of continuing to play whack-a-mole with parsing these values, we
are going to stop validating them entirely.
The special values 0x7D, 0x7E, and 0x7F (below sensitivity, saturated,
and not available) will be converted to atoms as before. All other
values will be treated as signed 8-bit integers. Values greater than
about -15dBm …
> Fix some more RSSI_REPORT quirks

- lib/grizzly/trace.ex
* Trace dumps used to be formatted in the `Grizzly.Trace` process. Because of this, any error writing a trace would crash the genserver, and all of the trace records would be lost. Formatting and writing dumps is now done in the calling process (typically a shell).
* Adds an option to write the trace dump in Erlang external term format.
> Refactor trace dump formatting

- lib/grizzly/commands/command.ex
Typical "good" Z-Wave RSSI values are in the -60..-80dBm range. It's rare to see anything below -50dBm unless the sending node's radio is at max transmit power and the receiving node is in physical contact with it.
On the other end of the range, most Z-Wave devices stop responding around -100dBm (the exact value will depend on many factors, but in a relatively quiet RF environment, this is the expected norm). Most devices remain responsive even with an RSSI as low as -95dBm, so dropping to 0 bars at -80dBm made very little sense.
Additionally, dBm is a logarithmic scale -- each 10dB interval represents a 10-fold change in power level, so a 3dB decrease is roughly equal to a halving of power.
| Bars | Previous Range | New Range     |
| ---- | -------------- | ------------- |
| 4    | >= …
> Update RSSI to signal bar calculation

- lib/grizzly/zwave/command_classes/multi_channel.ex
- lib/grizzly/zwave/command_classes/network_management_inclusion.ex
- lib/grizzly/zwave/commands/multi_channel_capability_report.ex
- lib/grizzly/zwave/commands/multi_channel_endpoint_find.ex
- lib/grizzly/zwave/commands/multi_channel_endpoint_find_report.ex
- lib/grizzly/zwave/device_classes.ex
- test/grizzly/zwave/command_classes/network_management_inclusion_test.exs
- test/grizzly/zwave/commands/extended_node_add_status_test.exs
- test/grizzly/zwave/commands/node_add_status_test.exs
Node Add Status should have the same behavior as Node Info Cached Get.
> Parse device classes in Node Add Status

- lib/grizzly/unsolicited_server/socket.ex
This definitely isn't an error.
> Reduce log level in UnsolicitedServer for closed connections

- lib/grizzly/autocomplete.ex
- mix.exs
Inspired heavily by https://github.com/elixir-toolshed/toolshed/blob/v0.2.26/lib/toolshed/autocomplete.ex
> IEx autocompletion for `Grizzly.send_command`

- lib/grizzly/transport_error.ex
- lib/grizzly/transports/DTLS.ex
Once we figure out what these errors are, maybe we can fix them. 😄
> Better logging for DTLS unexpected message errors

- lib/grizzly/connections/async_connection.ex
- lib/grizzly/connections/sync_connection.ex
- lib/grizzly/firmware_updates.ex
- lib/grizzly/firmware_updates/firmware_update_runner.ex
- lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
- lib/grizzly/inclusions.ex
- lib/grizzly/unsolicited_server.ex
- lib/grizzly/unsolicited_server/response_handler.ex
- lib/grizzly/unsolicited_server/socket.ex
- lib/grizzly/zipgateway/config.ex
- lib/grizzly/zwave/command_classes.ex
- lib/grizzly/zwave/commands/association_group_command_list_report.ex
- lib/grizzly/zwave/notifications.ex
`Logger.warn` is hard deprecated in Elixir 1.15.
> Replace `Logger.warn` with `Logger.warning`

- lib/grizzly/unsolicited_server/socket.ex
Previously, the unsolicited server was only sending ACKs to Z/IP Gateway
for messages when it was going to send a report in response. Messages
that were notified to subscribers or forwarded back to Z/IP Gateway were
never being acknowledged.
This resulted in Z/IP Gateway (sometimes) sending Application Busy
frames to devices when Grizzly had in fact received and handled the
corresponding message.
> Unsolicited server ACKs all messages

- lib/grizzly/zwave/command_classes/thermostat_operating_state.ex
The values from Thermostat v2 were missing.
> Add missing state values to Thermostat Operating State

- lib/grizzly/zwave/commands/battery_report.ex
Reserved fields should always be 0, but we don't need to validate that.
This also makes the recharge/replace bitfield more permissive. If bit 1 (recharge/replace now) is set, bit 0 (recharge/replace soon) is supposed to be set as well, but some devices only set bit 1. We can accept that value since there isn't much ambiguity there.
> Ignore reserved fields when parsing Battery Reports

- lib/grizzly/inclusions/zwave_adapter.ex
Allows consumers of `Grizzly.Inclusions` to pass command params like
`:tx_opt` when starting add node or learn mode.
> Pass params through to NodeAdd and SetLearnMode

- lib/grizzly/zipgateway/log_monitor.ex
- test/grizzly/zipgateway/log_monitor_test.exs
If a log line contains "SerialAPI: Retransmission" and the immediately
preceeding line contains "SerialAPI: Got RESPONSE while sending", then
the SAPI is obviously responding, so don't increment retransmission
counts in that case.
> Fix more false positives in SAPI status reporting

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/command_classes/meter.ex
- lib/grizzly/zwave/commands/meter_report.ex
- lib/grizzly/zwave/commands/meter_reset.ex
- lib/grizzly/zwave/commands/meter_supported_get.ex
- lib/grizzly/zwave/commands/meter_supported_report.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/meter_reset_test.exs
- test/grizzly/zwave/commands/meter_supported_get_test.exs
- test/grizzly/zwave/commands/meter_supported_report_test.exs
Commands added:
* MeterReset
* MeterSupportedGet
* MeterSupportedReport
> Implement missing Meter CC commands

- lib/grizzly/commands/table.ex
- lib/grizzly/zwave/commands/thermostat_setpoint_capabilities_get.ex
- lib/grizzly/zwave/commands/thermostat_setpoint_capabilities_report.ex
- lib/grizzly/zwave/decoder.ex
- test/grizzly/zwave/commands/thermostat_setpoint_capabilities_get_test.exs
- test/grizzly/zwave/commands/thermostat_setpoint_capabilities_report_test.exs
Required for Thermostat Setpoint v3
> Implement Thermostat Setpoint Capabilities Get/Report

- lib/grizzly/transports/DTLS.ex
Calling [`:ssl.handshake/1,2,3`](https://www.erlang.org/doc/apps/ssl/ssl.html#handshake/3) on a socket in active mode can result in undefined behavior.
> DTLS listen sockets start in passive mode

- lib/grizzly/zwave/commands/thermostat_setpoint_capabilities_report.ex
Adds special handling for malformed Tstat Setpoint Capabilities Reports
sent by Building36 B36-T10 / Alarm.com ADC-T2000.
> Handle malformed Thermostat Setpoint Capabilities Reports

- test/grizzly/commands/command_runner_test.exs
- test/grizzly/connections/keep_alive_test.exs
- test/grizzly/connections/sync_connection_test.exs
- test/grizzly/zwave/commands/zip_packet_test.exs
- test/grizzly/zwave/qr_code_test.exs
- test/grizzly_test.exs
* Found a couple tests that can be async
* Reduced unnecessarily long timeouts in several sync tests
> Fix some unnecessarily slow tests

- lib/grizzly/zwave/commands/zip_packet/header_extensions/installation_and_maintenance_report.ex
The Z-Wave spec says that speed is a byte and can only consist of the
values 0-4, but the value sent by Z/IP Gateway is a bitfield that
includes some additional information.
> Fix parsing of last working route speed in transmission stats

- lib/grizzly/firmware_updates/firmware_update_runner.ex
Because Z/IP Gateway does internal queueing, there's no way we can
guarantee the required delays between transmitting firmware image
fragments unless we wait for it to ack or nack the previous fragment.
> Wait for previous ack before continuing firmware upload

- lib/grizzly/unsolicited_server/socket.ex
This is a small patch to fix the bug addressed in #987 while I work on
the refactor.
> Prevent depletion of UnsolicitedServer listen sockets

- lib/grizzly/zwave/command_classes/network_management_inclusion.ex
- lib/grizzly/zwave/commands/extended_node_add_status.ex
- lib/grizzly/zwave/commands/node_add_status.ex
- test/grizzly/zwave/command_classes/network_management_inclusion_test.exs
- test/grizzly/zwave/commands/extended_node_add_status_test.exs
- test/grizzly/zwave/commands/node_add_status_test.exs
It is granted_keys to be consistent throughout
> Change keys_granted to granted_keys for consistency

- lib/grizzly/zwave/commands/multi_channel_endpoint_find_report.ex
- test/grizzly/zwave/commands/multi_channel_endpoint_find_report_test.exs
- test/grizzly_test.exs
Same deal as #998, but for the corresponding report command.
> Add :all to Multi Channel Endpoint Find Report

- lib/grizzly/zwave/notifications.ex
[SRH-1583]
[SRH-1583]: https://smartrent.atlassian.net/browse/SRH-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add a function to get all notification types

- lib/grizzly/inclusion_server.ex
> Inclusion Server handles Extended Node Add Status

- lib/grizzly/zwave/command_classes/sensor_multilevel.ex
[SRH-1582]
[SRH-1582]: https://smartrent.atlassian.net/browse/SRH-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Provide the possible scales for a given sensor type

- test/grizzly/zwave/commands/configuration_info_get_test.exs
- test/grizzly/zwave/commands/configuration_info_report_test.exs
> Fix wrong command bytes for configuration info get and report

- .circleci/config.yml
- .markdownlint-cli2.yaml
- .tool-versions
- CHANGELOG.md
- README.md
- docs/cookbook.md
I'm always forgetting to add link references to the bottom of the
changelog, and this will help with that.
> Lint markdown files
