smartrent/grizzly

lib/grizzly/command.ex
lib/grizzly/command/encode_error.ex
lib/grizzly/command_class/switch_binary.ex
lib/grizzly/command_class/switch_binary/set.ex
lib/grizzly/conn/server.ex
test/grizzly/command_class/switch_binary_test.exs
test/grizzly_test.exs

Provides the `Grizzly.Command.EncodeError` and an example of using it with the `SwitchBinary.Set` command.
Right now if there are bad values passed to a command for encoding then `send_command` crashes and Grizzly can get in an odd state, so the motivateion behind this is to help provide relaibilty and allow the user to decide if they should crash or handle this type of error in a particular way. 
Moving forward I would like to update all existing commands to use this, but can probably do that in PRs grouped by command class to make reviewing and testing maintainable.
This will be a breaking change once released so it would be nice to roll all the updates in one release to avoid too many breaking releases. 
refs: #31

Add command encode error

---

priv/zipgateway.tun

Things have changed slightly with new `zipgateway` 7.11 and what environment varia
bles are available when this script is called. So this adjusts the script slightly
to avoid using `pidof` and allows only 5 attempts before restarting the parent pr
ocess.

Adjust zipgateway.tun script to avoid pidof

---

README.md
lib/grizzly/application.ex

Remove the need to configure `pidof` via `busybox` and remove the
support in `Grizzly` to use the configured `pidof` since we don't
rely on `pidof` anymore.

Remove pidof docs and functions

---

lib/grizzly/command_class/network_management_basic.ex
lib/grizzly/command_class/network_management_basic/dsk_get.ex
lib/grizzly/packet/body_parser.ex
mix.exs
test/grizzly/command_class/network_management_basic/dsk_get_test.exs
test/grizzly/command_class/network_management_basic_test.exs
test/grizzly/packet/body_parser_test.exs

`DSKGet` get takes a `add_mode` argument because the controller can
return two different types of DSKs, one for when the device is in learn
mode and another for when the device is doing regular inclusion.

Support DSKGet command

---

README.md
lib/grizzly/application.ex
lib/grizzly/zipgateway_cfg.ex
test/grizzly/zipgateway_cfg_test.exs

When having Grizzly start zipgateway (useful for Nerves systems) we now
generate the `zipgateway.cfg` file before running the binary. This is
useful for device specific information like product id to be passed into
the configuration. Also, this will allow for optioning out of the
default scripts provided. If running in a Nerves system you can write
your own scripts and put them in the `rootfs_overly` directory and
provide that path to the script in the configuration.
The base configuration generated when there are no options provided is
the basic configuration that works in the Nerves environment.

Generate zipgateway.cfg from options passed in

---

lib/grizzly/command_class/network_management_basic.ex
lib/grizzly/command_class/node_provisioning/get.ex
lib/grizzly/command_class/node_provisioning/set.ex
lib/grizzly/dsk.ex
lib/grizzly/packet/body_parser.ex
mix.exs
test/grizzly/command_class/node_provisioning/get_test.exs
test/grizzly/command_class/node_provisioning/set_test.exs
test/grizzly/dsk_test.exs
test/grizzly/packet/body_parser_test.exs

These two commands give basic support to add DSKs to the node
provisioning list to allow for SmartStart devices. This gives
Grizzly basic SmartStart support.

Support NodeProvisioning SET and GET commands

---

lib/grizzly/command_class/mappings.ex
lib/grizzly/command_class/node_provisioning/meta_extension/product_type.ex
lib/grizzly/icon_type.ex
test/grizzly/command_class/node_provisioning/meta_extension/product_type_test.exs

Adds encoding and decoding of the SmartStart meta extension for product info.
This adds a fair amount of encoding and decode functionality, and the basics for the product type extension.
I will have follow up PRs for the other extensions and to tie the extensions into the decoding and encoding process with the rest of the `NodeProvisioning` command class.

SmartStart product type meta extension

---

lib/grizzly/smart_start/meta_extension/advanced_joining.ex
lib/grizzly/smart_start/meta_extension/bootstrapping_mode.ex
lib/grizzly/smart_start/meta_extension/location_information.ex
lib/grizzly/smart_start/meta_extension/max_inclusion_request_interval.ex
lib/grizzly/smart_start/meta_extension/name_information.ex
lib/grizzly/smart_start/meta_extension/network_status.ex
lib/grizzly/smart_start/meta_extension/product_id.ex
lib/grizzly/smart_start/meta_extension/product_type.ex
lib/grizzly/smart_start/meta_extension/smart_start_inclusion_setting.ex
lib/grizzly/smart_start/meta_extension/uuid16.ex
test/grizzly/smart_start/meta_extesion/advanced_joining_test.exs
test/grizzly/smart_start/meta_extesion/bootstrapping_mode_test.exs
test/grizzly/smart_start/meta_extesion/location_information_test.exs
test/grizzly/smart_start/meta_extesion/max_inclusion_request_interval_test.exs
test/grizzly/smart_start/meta_extesion/name_information_test.exs
test/grizzly/smart_start/meta_extesion/network_status_test.exs
test/grizzly/smart_start/meta_extesion/product_id_test.exs
test/grizzly/smart_start/meta_extesion/product_type_test.exs
test/grizzly/smart_start/meta_extesion/smart_start_inclusion_setting_test.exs
test/grizzly/smart_start/meta_extesion/uuid16_test.exs

Move the the meta extensions module out of the node provisioning command
class as they are not only used in that command class and Z-Wave
documentation has these under the SmartStart umbrella.

Move meta extesion modules to be under SmartStart namespace

---

lib/grizzly/command/encoding.ex
lib/grizzly/command_class/node_provisioning/get.ex
lib/grizzly/command_class/node_provisioning/set.ex
lib/grizzly/command_class/thermostat_setpoint.ex
lib/grizzly/packet/body_parser.ex
test/grizzly/command_class/node_provisioning/get_test.exs
test/grizzly/packet/body_parser_test.exs

Added the support to parse and provide SmartStart meta extensions
information to users when calling the commands in the NodeProvisioning
command class.
Had to make a fix to the encoding validation stuff, which showed a bug in our `TheremostatSetpoint.encode_setpoint_type` function, but the fix was trivial
so I just did it here.

Add NodeProvisioning command meta extension support

---

lib/grizzly/packet/body_parser.ex
test/grizzly/packet/body_parser_test.exs

When a DSK that is not part of the provisioning list was requested
the command would just hang. This fixes that by making the node
provisioning report the same for all binary strings that contain
a node provisioning report.

Fix timeout on NodeProvisioning.Get for missing DSK

---

lib/grizzly/conn/config.ex

Update the style to be easier to read (and following the [style of Elixir's docs](https://github.com/elixir-lang/elixir/blob/v1.9.4/lib/elixir/lib/gen_server.ex#L316-L337))
Also fixes some typos, adds the units for heart_beat_timer, as well as the recommended range.
[![](https://p196.p4.n0.cdn.getcloudapp.com/items/geurvOzZ/Screen+Shot+2019-11-30+at+3.08.31+PM.png?v=67620328e4a07ad7a3b40a997ad92cf8)](https://github.com/elixir-lang/elixir/blob/v1.9.4/lib/elixir/lib/gen_server.ex#L316-L337)

Update Grizzly.Conn.Config docs

---

lib/grizzly/unsolicited_server.ex

@fhunleth How about something like this to fix #138?
I've been liking the `handle_continue` pattern for this kind of stuff that needs to be part of `init` but non-blocking.
What do you think?

Handle ssl listen error on unsolicited server

---

lib/grizzly/command_class/switch_binary.ex
lib/grizzly/packet/body_parser.ex
test/grizzly/packet/body_parser_test.exs

AlloyHome BinarySwitches are V2 so this will help ensure they work with the SmartRent hub.
Better long support will be done as part of #29.

Support V2 binary switch

---

lib/grizzly/node.ex

This is a warning on Elixir 1.10.

Fix duplicate :security field

---

lib/grizzly/command_class/version.ex
lib/grizzly/packet/body_parser.ex
test/grizzly/command_class/version/get_test.exs
test/grizzly/command_class/version_test.exs
test/grizzly/packet/body_parser_test.exs

Instead of separate version and sub-versions in COMMAND_CLASS_VERSION CC

Report firmware versions as standard version.sub

---

lib/grizzly/packet/body_parser.ex

Fixed bug in parsing the packet for the firmware update md report v5

Fix to parsing FIRMWARE_UPDATE_MD report v5

---

lib/grizzly/inclusions/inclusion_runner.ex

If the plugin inclusion handler is applied in process and it calls back the Grizzly InclusionHandler (e.g. to grant keys), we get a "calling self" error.

spawn calls to inclusion handler else re-entrant

---

lib/grizzly/commands/command.ex
lib/grizzly/commands/command_runner.ex
lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/command_list.ex
lib/grizzly/connections/keep_alive.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/zwave/commands/zip_keep_alive.ex
lib/grizzly/zwave/commands/zip_packet/header_extensions.ex
lib/grizzly/zwave/commands/zip_packet/header_extensions/encapsulation_format_info.ex
test/grizzly/commands/command_runner_test.exs
test/grizzly/commands/command_test.exs
test/grizzly/connections/command_list_test.exs
test/grizzly/connections/sync_connection_test.exs
test/grizzly_test.exs
test/support/server.ex

Adds support for the queued commands.
When sending a command you get `{:queued, reference, queued_for_seconds}`
Z/IP pings an update about the remaining time every, 60 seconds, during that time there is a message sent in this form `{:grizzly, :queued_ping, reference, remaining_seconds}` where the reference is the same as the one return from the original `send_command` call.
Also, every 10 minutes there is a `ack_request` UDP ping from zipgateway to ensure there is someone still waiting for the command. So I added support for handling that.
If for some reason the command never gets sent at the time given to use by zipgateway you will receive a timeout like so:
`{:grizzly, queued_command_response, {:error, :timeout}`
All other responses are in this format too but with the response from the …

Fix queued commands

---

lib/grizzly/zwave/commands/battery_report.ex

battery level 0xFF is allowed => low battery warning

low battery warning

---

.circleci/config.yml
mix.exs

This also bumps the Elixir requirement in the mix.exs since pre-1.8
versions weren't being tested.

Test on supported versions of Elixir

---

mix.exs

This removes the long ex_doc build from the "dev" environment. If you
want to build docs, you have to be in the "docs" environment. That's
easy, though, since the `preferred_cli_env` will now default to there
when you run `mix docs` or `mix hex.publish`.

Move docs exclusively to the docs env

---

lib/grizzly/connections/command_list.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/inclusions/inclusion_runner.ex

When sending the same command to one node from two different processes
one command would be completed and the other would be marked as
completed as well, but that was wrong. Since both commands wait for the
same the report we one only complete one and allow the other to wait for
the next report that it is waiting for to allow it to be marked as
complete.

Fix when sending the same command to the same node

---

lib/grizzly/commands/table.ex
lib/grizzly/zwave/command_classes.ex
lib/grizzly/zwave/command_classes/zip_gateway.ex
lib/grizzly/zwave/commands/application_node_info_get.ex
lib/grizzly/zwave/commands/application_node_info_report.ex
lib/grizzly/zwave/commands/node_add_status.ex
lib/grizzly/zwave/decoder.ex
test/grizzly/zwave/command_classes_test.exs
test/grizzly/zwave/commands/application_node_info_get_test.exs
test/grizzly/zwave/commands/application_node_info_report_test.exs

```elixir
iex(20)> Grizzly.send_command(1, :application_node_info_get)
{:ok,
%Grizzly.ZWave.Command{
command_byte: 13,
command_class: Grizzly.ZWave.CommandClasses.ZIPGateway,
impl: Grizzly.ZWave.Commands.ApplicationNodeInfoReport,
name: :application_node_info_report,
params: [
command_classes: [
non_secure_supported: [:association_group_info],
non_secure_controlled: [],
secure_supported: [],
secure_controlled: []
]
]
}}
```
I had to update the command list encoding because if there is no controlled
command classes, then there is are no marks, for example, no `0xEF` or 
`0xF1 0x00` will not be in the command class report.
These two commands will allow us to both actually report and check that we
reporting the extra command classes to another controlling Z-Wave node.
There are two ways to …

Support getting and reporting application node info

---

lib/grizzly/zipgateway/zipgateway_cfg.ex
lib/mix/tasks/zipgateway.cfg.ex
test/grizzly/zipgateway/config_test.exs

Adds the necessary extra command classes to the configuration file and provides a mix task help to get some introspect to the zipgateway config that I have wanted for debugging reason in the past.
From the documentation generated from `make doc` on `zipgateway` source code.
Varifying this configuration works:
```elixir
iex(5)> Grizzly.send_command(1, :application_node_info_get)
{:ok,
%Grizzly.ZWave.Command{
command_byte: 13,
command_class: Grizzly.ZWave.CommandClasses.ZIPGateway,
impl: Grizzly.ZWave.Commands.ApplicationNodeInfoReport,
name: :application_node_info_report,
params: [
command_classes: [
non_secure_supported: [:association, :association_group_info,
:device_rest_locally, :multi_channel_association, :supervision,
:multi_cmd],
non_secure_controlled: [],
secure_supported: [], …
```

Set extra classes via zipgateway.cfg

---

lib/grizzly/zwave/commands/door_lock_operation_report.ex

The newly released Z-Wave specification updated the door lock operation
report timeout in minutes max minutes from `0xFC` to `0xFD`. This is a
fix in their documentation has they had stated that `253` (`0xFD`) is
valid. This should be no-op for most Grizzly users and will mostly add a
greater range of support for locks that contain `0xFD` in the report.
See `SDS13781 Z-Wave Application Command Class Specification.pdf`
provided by Silicon Labs document revision 15 for more information.

Update DoorLockOperationReport timeout for new spec

---

lib/grizzly/supervisor.ex
lib/grizzly/zipgateway/supervisor.ex

When the argument `:on_ready` is passed to the Grizzly supervisor it
will start a process that polls the connection to the Z-Wave controller
node until it gets a connection to let the consuming application know
that it can now safety control devices.
This moved the checker down to the last process to start to ensure that
the connection supervisor was up and running able to start new
connections to devices.

Fix connection supervisor not being ready for connection check

---

lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/supervisor.ex
lib/grizzly/transport.ex
lib/grizzly/transports/DTLS.ex
lib/grizzly/transports/UDP.ex
lib/grizzly/unsolicited_server.ex
lib/grizzly/unsolicited_server/messages.ex
lib/grizzly/unsolicited_server/socket.ex
lib/grizzly/unsolicited_server/socket_supervisor.ex
test/grizzly/unsolicited_server/messages_test.exs
test/support/UDP.ex

Refactor transport for these reason:
1. Support more than just DTLS
1. Allows for local development against the unsolicited server (useful for testing extra command support)
1. Has the unsolicited server and main connections use the same transport - cleans up duplicate code
1. Will allow with experimenting with disabling DTLS in the future

Refactor transport behaviour

---

lib/grizzly/transport.ex
lib/grizzly/transports/DTLS.ex
lib/grizzly/transports/UDP.ex
lib/grizzly/unsolicited_server.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/unsolicited_server/socket.ex
test/support/UDP.ex

If we have a command sent to us from another device on the network with the `:ack_request` flag we have to respond to the command with the `:ack_response` packet per Z-Wave spec.

Support sending ack responses in the unsolicated server

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/zip_packet.ex

This is the first pass at this functionality as when we can handle the
association set command we will actually send really data back.
This is mostly meant to help stub out the code for support more commands
from the Z-Wave PAN and some basic support for association get.

Handle when the association get command is received via PAN

---

lib/grizzly/zwave/commands/switch_binary_report.ex

This was creating warnings in when running `mix docs` and causing the
docs layout to break for the `SwitchBinaryReport` doc page.

Fix missing code markdown ` in docs

---

lib/grizzly/unsolicited_server.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/unsolicited_server/socket.ex
test/grizzly/unsolicited_server/response_handler_test.exs

This refactor allows for the testability of how Grizzly responses to
extra commands. Responding to extra commands correctly is important and
as such should be tested. Plus, some of the code became a bit hard to
reason about thus causing more risk to maintain.
This transforms the unsolicited server response handler to return data
structures rather than handling the broadcasting of notifications or
sending binary data to the Z-Wave network.
Also, makes an option for providing the associations server as an option
and allows for us to make testing more reproducible and limits the
amount of runtime dependencies.

Refactor extra command handling

---

lib/grizzly/commands/table.ex
lib/grizzly/network.ex

When the device Grizzly is running on network is reset, we have to send
the `DeviceResetNotification` command to the nodes that associated with
the lifeline association.

Send device reset notification

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/association_group_name_get.ex
lib/grizzly/zwave/commands/association_group_name_report.ex
test/grizzly/unsolicited_server/response_handler_test.exs

When a node requests an association group name we respond with the name
report for the lifeline association.
If the `group_id` name requested is not supported we are to respond with
the name report for the lifeline association. As of right now we are
going to support only the lifeline association so this codes will always
return with the lifeline association name.
Also, so nitpick clean up that has no effect on code functionality.

Support AssociationGroupNameGet in unsolicited server

---

lib/grizzly/unsolicited_server.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/unsolicited_server/socket.ex
test/grizzly/unsolicited_server/response_handler_test.exs

This will allow support for some commands that will need to have many
things happen after we handle it. For example the supervision get
command will need Grizzly to both notify any listeners and reply back
with the supervision report command.
Right now there is some code duplication. I hope this gets cleaned up
with future refactors and as we learn more how to better support these
extra commands.

Refactor ResponseHandler to return a list of actions to run

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/supervision_get.ex
lib/grizzly/zwave/commands/supervision_report.ex
test/grizzly/unsolicited_server/response_handler_test.exs

When the unsolicited command for supervision get, we use to just notify
listeners of the internal command that was sent, now we reply back with
the `SupervisionReport` command as outlined in the Z-Wave spec.
Also, did some clean up and switched the private functions in the
`ResponseHandler` module to return the `actions` list as outlined in the
type spec.

Support supervision get command fully for unsolicited server

---

lib/grizzly/commands/table.ex
lib/grizzly/unsolicited_server.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/unsolicited_server/socket.ex

This supports when the unsolicited server receives the multi command
encapsulated command.
It will inspect each command that in encapsulated.
If the command is part of the extra command classes we will pass that
long to the handler_command function for that command.
If the command is the `:alarm_report` we will still notify. We have to
provide this explicitly because we explicitly check the command against
the extra command classes so we are not blindly calling
`handler_command/2` function.
If the command does not meet either of those requirements we will tell
whoever is calling this function that they should pass it to the Z-Wave
controller (Z/IP Gateway) and send the report back that requesting node.

Support multi command encapsulated in unsolicited server

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/association_group_info_get.ex
lib/grizzly/zwave/commands/association_group_info_report.ex
test/grizzly/unsolicited_server/response_handler_test.exs

When the command for getting association group info comes in we response
by send the lifeline group info.

Support responding to AssociationGroupInfoGet via unsolicited server

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/association_group_command_list_get.ex
lib/grizzly/zwave/commands/association_group_command_list_report.ex
test/grizzly/unsolicited_server/response_handler_test.exs

Support when the `AssociationGroupCommandListGet` command is sent to the
unsolicited server.
It will always respond with the command list for the lifeline group as
of right we only support that group.

AssociationGroupCommandListGet support on unsolicited server

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/multi_channel_association_groupings_get.ex
lib/grizzly/zwave/commands/multi_channel_association_groupings_report.ex
test/grizzly/unsolicited_server/response_handler_test.exs

Unsolicited server will responding with the
`MultiChannelAssociationGroupingsGet` command with the report that
grouping `1` is support. As of right now that is the only grouping we
are trying to support.

Add support for the multi channel association grouping get

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/multi_channel_association_get.ex
lib/grizzly/zwave/commands/multi_channel_association_remove.ex
lib/grizzly/zwave/commands/multi_channel_association_report.ex
lib/grizzly/zwave/commands/multi_channel_association_set.ex
test/grizzly/unsolicited_server/response_handler_test.exs

This supports the multi channel association commands get, set, and
remove handling in the unsolicited server.
This assumes right now that the device using Grizzly does not support
multi channels and if I understand the specification correctly that
means we are to mirror how we support this in the non-multi channel
association command class.
There is some duplicate code here however, after more testing I will
imagine that code will be cleaned up as we get a better understanding of
the specification.

Support the multi channel association get, set, remove handling

---

.circleci/config.yml
mix.exs

When updating a consuming project to Elixir 1.11.2 there were warnings
about `EEx` not being a dependency, however we make calls to `EEx` for
generating commands and command class modules.
This lets the compiler know that we actually don't depend on `EEx`
when using Grizzly, as it is only leveraged during compile time/code
generation.

Update xref application boundaries for EEx

---

lib/grizzly.ex
lib/grizzly/connection.ex
lib/grizzly/connection_registry.ex
lib/grizzly/connections/binary_connection.ex
lib/grizzly/connections/supervisor.ex
lib/grizzly/transport.ex
lib/grizzly/transports/DTLS.ex
lib/grizzly/transports/UDP.ex
test/grizzly_test.exs
test/support/UDP.ex

This adds support for sending binary packets to a Z-Wave node.
This will enable control over packets that do not have a long lived
life cycle such as debugging packets and communication with other Z-Wave
nodes that send us commands.

Support sending binary packets

---

lib/grizzly/zwave/commands/zip_packet/header_extensions.ex
lib/grizzly/zwave/commands/zip_packet/header_extensions/encapsulation_format_info.ex
test/grizzly/zwave/commands/zip_packet/header_extensions_test.exs

From #396  I learned that the `crc16` flag was being added to the security level list which is not correct. Updated the code to have that flag marked separately so that we can parse and decode them without mashing them together. Added tests to ensure this both encoded and decoded correctly.

Fix when using crc16 in the Encapsulation Info header extension

---

lib/grizzly.ex
lib/grizzly/connection.ex
lib/grizzly/connection_registry.ex
lib/grizzly/connections/supervisor.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/network.ex
lib/grizzly/node.ex
lib/grizzly/unsolicited_server/socket.ex
lib/grizzly/zip_gateway.ex
lib/grizzly/zipgateway/ready_checker.ex
test/grizzly/zip_gateway_test.exs

This sends a binary response for commands that a received via the unsolicited server while the Z-Wave node isn't the main controller.
A problem Grizzly had was that it assumed that our gateway controller would always be node id 1, but when we are included in another controller's network that might be true.
A discovery uncovered that there is a PAN and LAN. The LAN will always be to the gateway and anytime we want to send a command to a node on the Z-Wave network we use the PAN. Since we can never know our controller's node id for sure this enables talking directly to the gateway by passing `:gateway` to send command.
I think that this will need to be iterated on a bit but unblocks us from testing and going through the certification process.

Send binary to respond from another controller

---

lib/grizzly.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/version_reports.ex
test/grizzly/unsolicited_server/response_handler_test.exs
test/grizzly_test.exs

There are two situations that we need to respond to extra commands:
1. From the Z-Wave PAN
2. From a user of Grizzly
For the first case the Z-Wave Z/IP packet will be forward to the
unsolicited destination server which will have to handle send back the
version command class report.
For the second case a user might call `Grizzly.send_command/4` to query
for a command class version.
Packets are only forward to the unsolicited destination server when the
come from the Z-Wave PAN network. For a user that calls `send_command`
the Z-Wave packet will never be forwarded to due this limitation (which
appears to be in place for security reasons). Since, the information for
the version reports are hardcoded information only we just respond to
callers of `send_command` directly without any Z-Wave …

Respond to version queries for extra commands

---

lib/grizzly.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/version_reports.ex

When sending a command class version get command to the gateway, we have
to send it via the LAN if the command is not an extra supported command
class.

Fix sending command class version get for non-extra cc

---

lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/binary_connection.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/zipgateway/ready_checker.ex

This removes all of the empty `GenServer.terminate/2` implementations
since they don't do any cleanup and the ones that only match `:normal`
obscure the reasons for abnormal crashes since they will raise.
Here's an example exception that was raised before this fix:
```
15:52:08.290 [error] GenServer {Grizzly.ConnectionRegistry, :gateway} terminating
** (FunctionClauseError) no function clause matching in Grizzly.Connections.SyncConnection.terminate/2
(grizzly 0.15.11) lib/grizzly/connections/sync_connection.ex:145: Grizzly.Connections.SyncConnection.terminate({:function_clause, [{Grizzly.Transports.DTLS, :parse_response, [{:ssl, {:sslsocket, {:gen_udp, {{{64768, 43690, 0, 0, 0, 0, 0, 1}, 41230}, #Port<0.289>}, :dtls_gen_connection}, [#PID<0.4272.0>]}, [35, 2, 64, 0, 237, 0, 0]}, []], …
```

Remove GenServer.terminate/2 to fix terminate crashes

---

lib/grizzly/transports/DTLS.ex

I believe that [this commit](https://github.com/erlang/otp/commit/f61c4302a8a5e6185e05d0f97d1c7bbc0d2621fc) in OTP broke this. The commit talks about TLS/DTLS-1.3 and refactoring out the generic parts of TLS and DTLS with version 1.2 and before.

Handle DTLS message change in OTP 23.2

---

lib/grizzly/transports/DTLS.ex

This is the unsolicited notification address and zipgateway requires
that all acknowledgments come from this IP address. This change forces
the address.
In theory, it should be passed as an option, but that's a more pervasive
change and it's never set to anything else.

Always bind the DTLS port to fd00:aaaa::2

---

lib/grizzly/unsolicited_server/socket.ex
lib/grizzly/zwave/commands/zip_packet.ex

When an extra command is sent to the unsolicited server this sends the
ack response. Also, this ensures that we are sending the command on the
same security encapsulation that we received the command on.

Send ack response for unsolicited commands

---

lib/grizzly/version_reports.ex
test/grizzly_test.exs

Update the version report for multi-channel association to be the
correct version number.

Set MultiChannelAssociation version to the correct one

---

lib/grizzly/associations.ex

The internal data structure for the associations is a map. When
deleting all the associations we were setting to an empty list which
would cause bugs later.

Fix associations to reset to a map

---

lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/supervisor.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/zipgateway/ready_checker.ex

These are due to zipgateway not being ready and they're ok. The strategy
is to retry later. This fixes crashes coming from this code that look
like this:
```
18:22:03.081 [error] GenServer Grizzly.ZIPGateway.ReadyChecker terminating
** (CaseClauseError) no case clause matching: {:error, {{:case_clause, {:error, :eaddrnotavail}}, [{Grizzly.Connections.SyncConnection, :init, 1, [file: 'lib/grizzly/connections/sync_connection.ex', line: 69]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 417]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 385]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}}
(grizzly 0.16.1) lib/grizzly/connections/supervisor.ex:52: Grizzly.Connections.Supervisor.do_start_connection/3
(grizzly 0.16.1) …
```

Support more that just timeout errors on DTLS failures

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/association_group_info_report.ex

In some cases we need to force the list mode bit to be set. This allows
us to do that but the fallback is to use derive this bit from the group
info param if this param is not set. This prevents a breaking change.

Add list mode param for AssociationGroupInfoReport

---

lib/grizzly/options.ex
lib/grizzly/supervisor.ex
lib/grizzly/zipgateway/config.ex
lib/grizzly/zipgateway/supervisor.ex
test/grizzly/zipgateway/config_test.exs

When using `zipgateway` version >= 7.14.2 it will rely on a database
file to save network and Z-Wave information.
You can pass the file path to the `Grizzly.Supervisor` via the
`:database_file` option but this does default to `/data/zipgateway.db`.
When migrating to a version that is >= 7.14.2 `Grizzly` will try to run
the `zgw_eeprom_to_sqlite` utility that is packaged with `zipgateway`.
The expected location for this utility is
`/usr/bin/zgw_eeprom_to_sqlite`.

Add support for a database file

---

lib/grizzly.ex
lib/grizzly/commands/table.ex

The first issue was the `DoorConfiguration` command was suppose to be
`DoorLockConfiguration`.
The second issue was we were comparing the atom version of the name
against the module version of the name, thus all commands would be
filtered out and returned list of commands would always be empty.
Closes: #413

Fix a bug that caused command discovery not to work

---

lib/grizzly/zwave/commands/firmware_md_report.ex
test/grizzly/zwave/commands/firmware_md_report_test.exs

Extra bytes at the end of the firmware_md_report binary params may need to be ignored

Fix to firmware_md_report

---

lib/grizzly/zipgateway/config.ex
lib/grizzly/zipgateway/supervisor.ex
test/grizzly/zipgateway/config_test.exs

Various tools that are part of the `zipgateway` ecosystem require
particular files to exist and to be in a writable location.

Ensure that required zipgateway files are written

---

lib/grizzly/zwave/commands/node_add_dsk_set.ex
lib/grizzly/zwave/dsk.ex
test/grizzly/zwave/dsk_test.exs

DSK.new/1 was untested. This fixes that.
The type spec for DSK.t() also requires that the binary be 128 bits
internally. This is nice since it means that DSK functions don't have to
worry about empty or short binaries. It, however, was not implemented
that way and binaries could be any even size between 0 and 16 bytes.

Ensure that the DSK binary is 128 bits; add test

---

lib/grizzly/zwave/commands/node_add_dsk_set.ex
lib/grizzly/zwave/dsk.ex
test/grizzly/zwave/dsk_test.exs

This adds `DSK.parse_pin/1` which is a friendlier way of handling PINs from
users and APIs. This pulls in the validity checking and removes the need to pad
zeros on strings.
The other function, `DSK.to_pin_string/1` reverses the process. Most
importantly it pads PINs with leading zeros which is a super easy mistake to
make.

Add PIN handling functions to DSK module

---

lib/grizzly.ex
lib/grizzly/switch_binary.ex

A higher level switch binary module to help users call higher level
functions.
Add a deprecation warning to help current know bout the change that
Grizzly is going to provide support for switch binary commands via the
`Grizzly.SwitchBinary` module and they should migrate to that.
See https://github.com/smartrent/grizzly/issues/478 for more details about
the ideas in this PR and where this might be heading.

Add SwitchBinary helper module

---

lib/grizzly/switch_binary.ex

This allows the send options like `:timeout` to be passed through to the
helpers in the `Grizzly.SwitchBinary` module.

Allow send options to be passed to SwitchBinary helper

---

lib/grizzly.ex
lib/grizzly/switch_binary.ex

As we move more commands into the higher level modules we should not log
the warning to use the higher level modules for those commands. This
adds a project level private function to do this until we have migrated
over.

Fix warning for helper modules

---

lib/grizzly/transports/DTLS.ex

OTP 24 has a new warning for whenever `:verify_none` is specified. This
is the main way of connecting to `zipgateway` and it's a local
connection anyway. This turns down the TLS warning level to avoid seeing
that message in the logs.

Turn off TLS warning when connecting to zipgateway

---

CHANGELOG.md

I updated the format of the changelog through releases that already had
a date along with the release number. These releases were somewhat
informed by keepachangelog.com and for that reason, I updated them to
fully be in that format and to remove markdown link warnings for that section
of the changelog.

Update CHANGELOG to follow keepachangelog

---

lib/grizzly/commands/command.ex

Deal with nil rssi_hops.
Shouldn't no rssi data give 0 bars instead of 4?

Fixes to transmission stat calcs

---

lib/grizzly/network.ex

This helper function ensures the correct meta extensions are set for a
long range device to be correctly added to the node provisioning list.
Here's the log of the node joining the network after I used this function:
```
18:58:45.251 [debug] /usr/sbin/zipgateway: 185428 nm_fsm_post_event event: NM_EV_ADD_NODE_FOUND state: NM_WAITING_FOR_ADD
18:58:45.415 [debug] /usr/sbin/zipgateway: 185592 nm_fsm_post_event event: NM_EV_ADD_SLAVE state: NM_NODE_FOUND
18:58:45.416 [debug] /usr/sbin/zipgateway: 185593 Inclusion timeout (based on the network nodes) calculated is: 76217
18:58:45.422 [debug] /usr/sbin/zipgateway: 185594 nm_fsm_post_event event: NM_EV_ADD_PROTOCOL_DONE state: NM_WAIT_FOR_PROTOCOL
18:58:45.435 [debug] /usr/sbin/zipgateway: 185612 nm_fsm_post_event event: …
```

Add long range provisioning list helper

---

lib/grizzly/zwave/commands/node_list_report.ex
lib/grizzly/zwave/node_id_list.ex
test/grizzly/zwave/node_id_list_test.exs

This refactors our parsing of the node list binary. This type of code is
used in various places of Grizzly so providing an internal module to
reuse will provide useful. A follow up PR will made to update the parts
of code that would use this module.
This also handles parsing the node list binary bit mask for extended
node ids in support of Z-Wave long range.
Closes: #482

Support extended node ids in node list report

---

lib/grizzly/zwave/commands/failed_node_list_report.ex
lib/grizzly/zwave/node_id_list.ex
test/grizzly/zwave/commands/failed_node_list_report_test.exs
test/grizzly/zwave/node_id_list_test.exs

This change proves support for parsing and encoding extended node ids
for failed node list report. This also moves the encoding logic to the
NodeIdList module to better provide code reuse for encoding node id
lists correctly. This logic is located in other parts of the code, so
follow up changes will update the other places in the code that can use
this encoding logic.
Closes: #489

Support extended node ids in failed node list report

---

lib/grizzly/zwave/command_classes/network_management_inclusion.ex
lib/grizzly/zwave/commands/failed_node_remove.ex
lib/grizzly/zwave/commands/node_remove_status.ex
test/grizzly/zwave/command_classes/network_management_inclusion_test.exs
test/grizzly/zwave/commands/failed_node_remove_test.exs

- Add helpers for encoding and parsing node remove node ids
- Support v4 FailedNodeRemove
Closes: #480

fail node remove extended id

---

lib/grizzly/zwave/command_classes/network_management_inclusion.ex

The specification only specifies this is some areas while not saying
much about these bytes in others. While all manual testing has shown
these bytes to be `<<0x00, 0x00>>` when there is an 8 bit node id, that
does not mean they will always be that way.
We know when the node id is an extended node id by the `0xFF` at the
byte index for the 8 bit node id.
By just ignoring these fields and we get a bit more flexibility to what
might come over the wire in those fields. Again, we will know to look at
those bytes if the `0xFF` byte is the right place, otherwise we can
safely ignore them and prevent any hard to track down match errors in
the future.

Ignore extra 2 bytes in extended node id binary string

---

lib/grizzly/zwave/node_id_list.ex
test/grizzly/zwave/commands/failed_node_list_report_test.exs

Adds a match for when the extended node id list length byte is set to 0.

Fix when FailedNodeListReport does not contain extended node ids

---

lib/grizzly/zwave/commands/s2_resynchronization_event.ex
test/grizzly/zwave/commands/s2_resynchronization_event_test.exs

This adds the ability to parse extended node ids in the
S2ResynchronizationEvent command.

Add support S2ResynchronizationEvent command version 3

---

lib/grizzly.ex
lib/grizzly/commands/command.ex
lib/grizzly/commands/command_runner.ex
test/grizzly/commands/command_runner_test.exs

When sending messages to a wake up device, while the device is sleeping
the command gets queued in zipgateway's mailbox. The mailbox can only
contain 2000 entries by all devices on a network. If a command is sent
and is queued into the mailbox but the mailbox has hit capacity the
command is dropped and the device will never receive it.
This fixes an issue were Grizzly was not matching on this error when
receiving a Z/IP Packet from zipgateway that contains the
`:nack_queue_full` flag.

Fix crash when zipgateway responds with queue full

---

lib/grizzly/network.ex

Was missing an error case that's triggered when, for example, firmware is updating.

Handle errors on getting failed nodes

---

lib/grizzly/firmware_updates/firmware_update_runner.ex

Fixes
`11:33:22.812 [error] GenServer Grizzly.FirmwareUpdates.FirmwareUpdateRunner terminating
** (FunctionClauseError) no function clause matching in Grizzly.FirmwareUpdates.FirmwareUpdateRunner.handle_info/2
(grizzly 0.22.6) lib/grizzly/firmware_updates/firmware_update_runner.ex:119: Grizzly.FirmwareUpdates.FirmwareUpdateRunner.handle_info({:error, :nack_response}, %Grizzly.FirmwareUpdates.FirmwareUpdateRunner.FirmwareUpdate{activation_may_be_delayed?: false, current_command_ref: #Reference<0.1726771937.2368733185.225652>, device_id: 58, firmware_id: 42400, firmware_target: 0, fragment_index: 549, fragments_wanted: 0, handler: Piston.FirmwareUpdateHandler, hardware_version: 2, image: %Grizzly.FirmwareUpdates.FirmwareUpdateRunner.Image{fragments: [<<235,`

Handle :nack_response when updating fw

---

lib/grizzly/zwave/commands/association_group_command_list_report.ex
test/grizzly/zwave/commands/association_group_command_list_report_test.exs

Ignores bytes added by some devices beyond the advertized commands count

association group command list report fix

---

lib/grizzly/firmware_updates/firmware_update_supervisor.ex
lib/grizzly/zwave_firmware.ex

To support Hubview requesting hub z-wave firmware upgrades, Piston needs to be able to aks Grizzly about the potential firmware info upgrades.

Provide controller firmware upgrade info

---

lib/grizzly/zwave/notifications.ex

The Kwikset 916 locks does not encapsulate a UserCodeReport as alarm report parameters on access control notifications for keypad_lock_operation and keypad_unlock_operation events. It only gives a user id as a single byte.

When only user code id in access control alarms

---

lib/grizzly/commands/table.ex
lib/grizzly/zwave/command_classes/network_management_installation_maintenance.ex
lib/grizzly/zwave/commands/priority_route_report.ex
test/grizzly/zwave/commands/priority_route_report_test.exs
test/grizzly/zwave/commands/statistics_report_test.exs

Fixed typo in command table for :priority_route_get
Speed byte is a mask encoding one or more speeds, not just one

Fixes for priority route and statistics commands

---

README.md
lib/grizzly.ex
lib/grizzly/network.ex
lib/grizzly/node.ex
lib/grizzly/report.ex
lib/grizzly/supervisor.ex
lib/grizzly/virtual_devices.ex
lib/grizzly/virtual_devices/device.ex
lib/grizzly/virtual_devices/device_server.ex
lib/grizzly/virtual_devices/devices_supervisor.ex
lib/grizzly/virtual_devices/network.ex
lib/grizzly/virtual_devices/thermostat.ex
lib/grizzly/virtual_devices_supervisor.ex
lib/grizzly/zwave/device_class.ex
mix.exs
test/grizzly/virtual_devices_test.exs
test/grizzly_test.exs
test/support/virtual_device_case.ex

Base support for virtual devices.
Since zip gateway does not provide a way for us to directly add virtual devices to the Z-Wave network, I added this feature to Grizzly.
The PR's goal is to setup the basic OTP infrastructure and modules needed for virtual devices. Two follow up PRs are next:
1. To finish the implementation of the thermostat
2. Provide some disk back options for virtual devices, so the devices stay in the virtual network over reboots.

Add support for virtual devices

---

lib/grizzly/virtual_devices/thermostat.ex

An unimplemented command of a virtual device should cause a time out error instead of a crash.

Timeout unimplemented virtual device command

---

lib/grizzly/zwave/smart_start/meta_extension.ex
test/grizzly/zwave/smart_start/meta_extensions_test.exs

SmartStart network_status meta extension has two additional bytes to encode the long range node id.

Fix to a meta-extension changed by long range

---

lib/grizzly/zwave/commands/configuration_set.ex
test/grizzly/zwave/commands/configuration_set_test.exs

Configuration parameter values are now checked against allowed ranges given their byte sizes when set.
Also, only byte sizes 1,2 and 4 are now allowed, as per the Z-Wave specs.

Validate signed configuration parameter values

---

lib/grizzly/virtual_devices/device.ex
lib/grizzly/virtual_devices/temperature_sensor.ex
lib/grizzly/virtual_devices/thermostat.ex
test/grizzly/virtual_devices/thermostat_test.exs
test/grizzly/virtual_devices_test.exs

Allow for virtual devices to be started before Grizzly itself starts.
Virtual devices will be started and supervised in platform support libraries/applications (e.g. parakeet_support), which start before either Piston or Grizzly. The virtual device servers (pids) will be passed to Piston to carry out the inclusion process . The inclusion process is started by Piston adding a virtual device in Grizzly and then handling the inclusion callback.
All this to say that virtual devices must not add themselves to the virtual network when they start.

Virtual devices cleanup

---

lib/grizzly/inclusions/zwave_adapter.ex

Else we get an error when timing out on providing a requested DSK PIN
```
18:49:24.914 [error] GenServer Grizzly.InclusionServer terminating
** (FunctionClauseError) no function clause matching in Grizzly.Inclusions.ZWaveAdapter.handle_timeout/3
(grizzly 5.1.2) lib/grizzly/inclusions/zwave_adapter.ex:142: Grizzly.Inclusions.ZWaveAdapter.handle_timeout(:dsk_input_set, #Reference<0.3940735786.1738276865.248287>, %{command_ref: #Reference<0.3940735786.1738276865.249871>})
(grizzly 5.1.2) lib/grizzly/inclusion_server.ex:234: Grizzly.InclusionServer.handle_info/2
(stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4
(stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6
(stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:grizzly, :report, …
```

Handle timeout on DSK input during inclusion

---

lib/grizzly/zwave/command_classes/thermostat_setpoint.ex
test/grizzly/zwave/commands/thermostat_setpoint_set_test.exs

While digging around I noticed spellings for both `celcius` and `celsius`. 
I don't know what this change impacts but I changed it to be consistent 😅 Can someone help test to make sure this doesn't break anything? 😆

Bugfix: Typo For Celsius

---

lib/grizzly/inclusion_server.ex
lib/grizzly/inclusions.ex
lib/grizzly/inclusions/network_adapter.ex
lib/grizzly/inclusions/status_server.ex
lib/grizzly/inclusions/supervisor.ex
lib/grizzly/supervisor.ex
test/grizzly/inclusions_test.exs
test/support/test_network_adpater.ex

We isolate the inclusion status from the inclusion logic process in order
to restore the inclusion process back to a working state in case of
runtime errors in the main inclusion process.
This fixes a bug where the inclusion process would be restored back to
an idle state, but the Z-Wave controller is still in inclusion mode.

Isolate inclusion status from inclusion logic

---

lib/grizzly/inclusions/zwave_adapter.ex

I am not certain about this fix because I don't understand why handling node_removing timeouts matches on command references while other handle_timeouts don't.

Fix to handling timeout of node removing

---

.circleci/config.yml
lib/grizzly/zwave/command_classes/barrier_operator.ex
lib/grizzly/zwave/command_classes/network_management_installation_maintenance.ex
lib/grizzly/zwave/commands/thermostat_setpoint_supported_report.ex

- `use Bitwise` is deprecated in favor of `import Bitwise`.
- Added Elixir 1.14 / OTP 25 to CircleCI config

Fix Elixir 1.14 deprecation warnings

---

lib/grizzly/zwave/notifications.ex

For the notification command class, the state_idle notification can be used to indicate that one of the state variable for a notification type has returned to idle.
For home security, this means that both a motion detected idle and a tamper cover removed idle event will have an event of state_idle. The way to differentiate this is by looking at the event parameters.
This implements decoding of event parameters for home security events so that consumers can determine _which_ state variable has returned to idle.
---
```elixir
iex(1)> Grizzly.ZWave.Commands.AlarmReport.decode_params(<<0x00, 0x00, 0x00, 0xFF, 0x07, 0x00, 0x01, 0x03>>)
{:ok,
[
type: 0,
level: 0,
zensor_net_node_id: 0,
zwave_status: :enabled,
zwave_type: :home_security,
zwave_event: :state_idle,
event_parameters: [state: …
```

Implement event parameter decoding for home security idle notifications

---

lib/grizzly/transports/DTLS.ex

This also fixes a typo where the IP address was printed instead of the port.

Format IPv6 addresses in traces using standard port notation

---

lib/grizzly/transports/DTLS.ex

All of these are guaranteed to return :ok. Perhaps it was needed in an
earlier version of code.

Remove unneeded code to ignore return values

---

lib/grizzly/transports/DTLS.ex

Outgoing traces are sent to the destination node's IPv6 address, not to Grizzly's.

Record correct node IP for outgoing traces

---

lib/grizzly/zwave/commands/node_add_dsk_report.ex
lib/grizzly/zwave/commands/node_add_keys_set.ex
test/grizzly/trace/record_test.exs

`Grizzly.Trace.dump/1` would crash if you had recently included an S2 device due to errors encoding/decoding the `NODE_ADD_DSK_REPORT` and `NODE_ADD_KEYS_SET` commands.

Fix trace dump crashes after including S2 devices

---

lib/grizzly/inclusion_server.ex
lib/grizzly/inclusions.ex

Attempting to stop add/remove/learn mode while already idle is a no-op and should not act like other error conditions.
Also updates specs to indicate that the inclusion server's status can be returned if the inclusion server is not in a valid state for the requested operation.

Stopping inclusion while idle should return `:ok`

---

lib/grizzly/command_handlers/aggregate_report.ex
lib/grizzly/commands/table.ex
lib/grizzly/zwave/commands/configuration_name_get.ex
lib/grizzly/zwave/commands/configuration_name_report.ex
lib/grizzly/zwave/decoder.ex
test/grizzly/zwave/commands/configuration_name_get_test.exs
test/grizzly/zwave/commands/configuration_name_report_test.exs

```
iex(19)> Grizzly.send_command(56, :configuration_name_get, [param_number: 15])
{:ok,
%Grizzly.Report{
status: :complete,
command: %Grizzly.ZWave.Command{
name: :configuration_name_report,
command_byte: 11,
command_class: Grizzly.ZWave.CommandClasses.Configuration,
params: [
name: "Reset To Factory Defaults",
param_number: 15,
reports_to_follow: 0
],
impl: Grizzly.ZWave.Commands.ConfigurationNameReport
},
transmission_stats: [],
queued_delay: 0,
command_ref: #Reference<0.1319199483.2911895553.38824>,
node_id: 56,
type: :command,
queued: false
}}
```

Support getting configuration parameter name

---

lib/grizzly/inclusion_server.ex
lib/grizzly/inclusions/status_server.ex
lib/grizzly/inclusions/zwave_adapter.ex
lib/grizzly/zwave/command_classes/network_management_inclusion.ex

`Grizzly.InclusionServer` was failing to recover properly after a crash.
The expected behavior is that `InclusionServer` cancels any active add/remove/learn mode (as reported by `Grizzly.Inclusions.StatusServer`) when it starts. For some reason, the command to do this always seems to time out on the first attempt, but the `InclusionServer` was never retrying.
This introduces the following changes in behavior:
- `InclusionServer`'s init recovery will run even when `StatusServer` reports that inclusion mode is already being canceled
- If a command to cancel inclusion mode times out, it will be repeated
These changes provide the quickest recovery path. However, if the issue persists in other cases, it may make sense for `StatusServer` to implement its own internal timeout based on the …

Improve InclusionServer crash recovery from non-idle status

---

lib/grizzly/zwave/command_classes/network_management_installation_maintenance.ex
test/grizzly/zwave/commands/rssi_report_test.exs

This also fixes a bug wherein the Z-Wave spec says that valid RSSI values will be in the range `0xE0..0x80` (signed), but we were allowing only a subset `0xE0..0xA2`.
Fixes #702

Handle illegal values from Z/IP Gateway in RSSI_REPORT

---

test/grizzly/inclusions_test.exs

When inclusion is running, all commands will fail with `{:error, including}`.
This should fix some (if not all) of the flaky tests.

Inclusions tests should not be async

---

lib/grizzly/zwave/command_classes/thermostat_setpoint.ex
lib/grizzly/zwave/commands/thermostat_setpoint_report.ex
lib/grizzly/zwave/commands/thermostat_setpoint_set.ex

`ThermostatSetpointReport.param()` was missing `{:value, integer()}`.

Fix typespec for `ThermostatSetpointReport` params

---

lib/grizzly/zwave/command_classes/network_management_installation_maintenance.ex

In #705, we fixed the decoding of the full range of expected RSSI
values, but we missed re-encoding. This is normally not a problem
because Grizzly typically only decodes RSSI_REPORTs, but this will cause
calls to `Grizzly.Trace.dump/1` raise an error if an RSSI_REPORT with an
out-of-range value exists in the trace buffer.

Fix RSSI encoding

---

lib/grizzly/trace/record.ex

There is a bug in writing trace dumps when a command in the trace buffer
is not a Z/IP Packet encapsulated command. It's unclear what command(s)
are involved as the issue seems somewhat rare.
Until we can pin down the issue, this should prevent trace dumps from
crashing under the described circumstances and provide debugging
information for a future fix.

Handle errors raised when writing trace dumps

---

lib/grizzly/commands/table.ex
lib/grizzly/virtual_devices.ex
lib/grizzly/zwave/commands/node_info_cached_get.ex
test/grizzly/zwave/commands/node_info_cached_get_test.exs

Several commands had names that did not match the command name in the
command returned from the implementation's `new/1` function. Several
other commands were pointing to the wrong implementation module and
never would have worked properly.
This adds simple validation to `Grizzly.Commands.Table` to ensure that
(outside of a few exceptions) the command name in the table matches the
command name in the implementation module.

Validate command names in `Grizzly.Commands.Table`

---

.circleci/config.yml
lib/grizzly.ex
lib/grizzly/command_handlers/supervision_report.ex
lib/grizzly/commands/command.ex
lib/grizzly/commands/table.ex
lib/grizzly/connections/command_list.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/report.ex
lib/grizzly/session_id.ex
lib/grizzly/supervisor.ex
mix.exs
test/grizzly/command_handlers/supervision_report_test.exs
test/grizzly/commands/command_test.exs
test/grizzly/session_id_test.exs
test/grizzly_test.exs
test/support/server.ex
test/test_helper.exs

```elixir
iex(5)> Grizzly.can_supervise_command?(:door_lock_operation_get)
false
iex(6)> Grizzly.can_supervise_command?(:door_lock_operation_set)
true
```
```elixir
iex(2)> Grizzly.send_command(46, :user_code_set, [user_id: 5, user_code: "123456", user_id_status: :occupied], supervision?: true)
{:ok,
%Grizzly.Report{
status: :complete,
command: %Grizzly.ZWave.Command{
name: :supervision_report,
command_byte: 2,
command_class: Grizzly.ZWave.CommandClasses.Supervision,
params: [
more_status_updates: :last_report,
session_id: 31,
status: :success,
duration: 0
],
impl: Grizzly.ZWave.Commands.SupervisionReport
},
transmission_stats: [],
queued_delay: 0,
command_ref: #Reference<0.1484145361.3358588929.238507>,
node_id: 46,
type: :command,
queued: false
}}
```
```elixir
iex(3)> …
```

Add support for sending supervised commands

---

lib/grizzly/connections/sync_connection.ex
lib/grizzly/unsolicited_server/socket.ex
lib/grizzly/zwave/commands/zip_packet.ex

This is necessary for wakeup devices to receive the supervision report
before they go back to sleep.

Set more info flag when ACKing supervision get commands

---

lib/grizzly.ex

This is needlessly causing alarm as a warning

Downgrade level of log to upgrade command impl

---

priv/zipgateway.tun

Z/IP Gateway was failing to start up due to an issue with setting routes
on the tun/tap network interface. Setting the interface to down and
restarting the `zipgateway` process fixed this. In order to prevent this
from happening in the future, this updates the tunnel setup script to
bring the interface down first and then bring it up. Doing so should
clean up state in the Linux kernel and hopefully make setting up the
tun network more reliable. In theory, it also brings the network down if
requested to also remove routing table state.

Reset tun/tap interface by marking it down

---

lib/grizzly/zwave/commands/switch_multilevel_report.ex
test/grizzly/zwave/commands/switch_multilevel_report_test.exs

A Leviton DZ1KD-1BZ dimmer reports 100 for 100% on. According to the
Z-Wave spec, this really should be 99. The decoder crashes with the
following, though:
```
** (MatchError) no match of right hand side value: {:error, %Grizzly.ZWave.DecodeError{value: 100, param: :value, command: :switch_multilevel_report}}
(grizzly 6.4.0) lib/grizzly/zwave/commands/zip_packet.ex:83: Grizzly.ZWave.Commands.ZIPPacket.decode_params/1
(grizzly 6.4.0) lib/grizzly/zwave/decoder.ex:1: Grizzly.ZWave.Decoder.decode/2
(grizzly 6.4.0) lib/grizzly/transports/DTLS.ex:129: Grizzly.Transports.DTLS.handle_ssl_message_with_ip/4
(grizzly 6.4.0) lib/grizzly/connections/sync_connection.ex:133: Grizzly.Connections.SyncConnection.handle_info/2
(stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
(stdlib 4.3) …
```

Normalize a Leviton dimmers incorrect value report

---

README.md
docs/cookbook.md
lib/grizzly/zwave/command_classes/zwaveplus_info.ex
lib/grizzly/zwave/commands/version_report.ex
lib/grizzly/zwave/device_class.ex
lib/grizzly/zwave/device_classes.ex
lib/grizzly/zwave/icon_type.ex
test/grizzly/virtual_devices_test.exs

Temporarily reverts smartrent/grizzly#746 until we're ready to do a major release.

Revert "Replace "slave" with "end node""

---

lib/grizzly/zwave/command_classes/network_management_inclusion.ex
lib/grizzly/zwave/commands/node_add_status.ex
lib/grizzly/zwave/commands/zip_packet.ex

... even when it's empty. Also updates Node Add Status encoding to match
the decoding behavior updated in #759.

Node Add Status always includes command classes list

---

lib/grizzly/commands/command.ex
test/grizzly/commands/command_test.exs
test/grizzly/connections/command_list_test.exs

Grizzly's retries are currently opaque to consumers, which can cause
issues if consumers implement their own retry mechanism. This makes
retries opt-in instead of opt-out.

Do not retry commands by default

---

lib/grizzly/zwave/commands/configuration_report.ex

A payload of `<<1, 1, 0, 0>>` was observed coming from a Yale YRD-642 ZW3. Instead of crashing, we'll drop any unexpected bytes and log a warning.

Do not crash on trailing bytes in ConfigurationReport

---

.circleci/config.yml
lib/grizzly/zwave/commands/thermostat_setpoint_set.ex
test/grizzly/connections/sync_connection_test.exs
test/grizzly/zwave/commands/thermostat_setpoint_set_test.exs

The Thermostat Setpoint Set CC uses signed values in its binary
encoding, but we were encoding and decoding values as unsigned.
On top of being incorrect, the calculation for the number of bytes
needed to encode the value would raise an error for any negative number
(because log-n is undefined for values <= 0).

Support signed values in Thermostat Setpoint Set

---

lib/grizzly/zwave/commands/switch_multilevel_report.ex
test/grizzly/zwave/commands/switch_multilevel_report_test.exs

Instead of [crashing](https://smartrent.sentry.io/issues/4190192493/?project=4505127406141440&referrer=slack) when more than 3 bytes are received log a warning and return a `%DecodeError{}`

Handle trailing bytes in SwitchMultilevelReport

---

README.md
lib/grizzly.ex
lib/grizzly/unsolicited_server/messages.ex

It is currently possible to subscribe to one or more unsolicited
commands from all nodes. This makes it possible to do the inverse:
subscribe to all commands from a single node.

Allow subscribing to all unsolicited events from a node

---

lib/grizzly.ex
lib/grizzly/commands/command_runner.ex

From my own observations, this is how long before the Z-Wave module
actually gives up when sending a command to an offline/failed node.

Increase default command timeout to 15s

---

lib/grizzly/transports/DTLS.ex

This enables support for versions of Z/IP Gateway compiled against
OpenSSL 3.0.

Allow DTLSv1.2

---

lib/grizzly/trace.ex
lib/grizzly/trace/record.ex
test/grizzly/trace_test.exs

Z/IP KeepAlive frames are fairly noisy and recording them is really only
useful for debugging the keepalives themselves. Keepalive frames can
quickly fill the trace buffer, especially in networks with many active
nodes.
This also makes a minor change to the default trace format to include the
expected delay field when printing nack+waiting Z/IP Packet frames.

Trace option to ignore keepalive frames

---

config/config.exs
lib/grizzly.ex
lib/grizzly/connection.ex

This allows callers to force Grizzly to send a command in async mode by
calling `Grizzly.send_command(node, :command, params, mode: :async)`.
The `:mode` option is now passed through from `Grizzly.send_command/4`
to `Grizzly.Connection.open/2`. `Grizzly.Connection.send_command/3` has
had its `:type` option renamed to `:mode` for consistency (`:type` will
be used as a fallback to maintain backwards compatibility).

Allow `:mode` option in `Grizzly.send_command/4`

---

lib/grizzly/autocomplete.ex
test/grizzly/autocomplete_test.exs

This improves command autocompletion in cases like `Grizzly.send_command(variable, :thermostat<TAB>`.

Use AST for autocompletion

---

.circleci/config.yml
lib/grizzly/trace/record.ex
lib/grizzly/zwave/commands/zip_packet.ex
mix.exs
test/grizzly/trace/record_test.exs

Previously, the `:text` trace format printed command parameters by
re-encoding them using the command module. This had two major issues:
1. There are many commands that controllers do not typically send, and
thus Grizzly does not encode except when printing traces. We were
occasionally running into cases where we could decode a command but
hit bug when re-encoding it.
2. There are some commands whose encoding and decoding functions are not
invertable. This can be due to amgibuity between command class
versions in the spec or because of allowances made for devices that
fail to follow the spec. In the latter case, it is particularly
important that traces print the command binary exactly as it was
received.
Going forward, the `:text` trace format will print the full command
binary (including …

Trace prints command binary exactly as received

---

lib/grizzly/network.ex
lib/grizzly/node.ex
lib/grizzly/zwave/commands/node_info_cached_get.ex

* Most functions in `Grizzly.Network` and `Grizzly.Node` now allow
specifying send command options (`t:Grizzly.command_opt/0`)
* `Grizzly.Node.get_info/2` now supports specifying the max age
parameter
* Node info cached get's max age parameter now uses `:infinity` instead
of `:infinite` to be more consistent with Elixir's standard library

Make network management command arguments more consistent

---

lib/grizzly/zwave/commands/meter_report.ex

All versions of the Meter command class specify this field as a full
byte, not 5 bits.

Fix decoding of meter type in Meter Reports

---

lib/grizzly/connections/async_connection.ex

Handling a command timeout in AsyncConnection was expecting a `GenServer.from()` structure for the waiter, but it stores only the waiter pid so the match would fail when trying to get the pid out of the `from`
This fixes those timeout cases by using the waiter pid as is

Fix async command timeout

---

lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave/commands/multi_channel_association_report.ex
test/grizzly/zwave/commands/multi_channel_association_report_test.exs

We weren't providing all of the required parameters when constructing
the Multi Channel Association Report response. Additionally, the
encoding of that command was incorrect in cases where the controller has
zero node endpoints (so always).

Fix response handler for Multi Channel Association Get

---

lib/grizzly/zwave/commands/sensor_multilevel_report.ex

It was encoded and decoded unsigned.
[SRH-666] and [SRH-832]
[SRH-666]: https://smartrent.atlassian.net/browse/SRH-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SRH-832]: https://smartrent.atlassian.net/browse/SRH-832?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

The value in sensor_multilevel_report is signed

---

lib/grizzly/zwave/commands/door_lock_operation_report.ex

A real device was sometimes adding 2 extra bytes. No idea why, but the
frame was otherwise valid (and correct).

Ignore extra bytes at the end of Door Lock Operation Report

---

lib/grizzly/zipgateway/ready_checker.ex
lib/grizzly/zipgateway/supervisor.ex
test/grizzly/zipgateway/ready_checker_test.exs

Z/IP Gateway sends an unsolicited Node List Report when it is far enough
along in its initialization process to receive commands. Instead of
testing that we can merely open a connection, we'll wait for that
signal.
If we don't receive it after 60 seconds (and every 60 seconds thereafter
until success), we'll try to get the node list ourselves.

Z/IP Gateway ready checker waits for initial node list report

---

lib/grizzly/transports/DTLS.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/unsolicited_server/socket.ex
lib/grizzly/zwave/commands/zip_packet.ex

Previously, we were replying to unsolicited commands on a new or
already-established DTLS connection via `Grizzly.send_command` or
`Grizzly.send_binary`.
This frequently resulted in Z/IP Gateway sending the reply from a
different virtual node ID (and potentially incurring a fresh S2 nonce
exchange).
This also fixes a long-standing bug where any replies sent from the
unsolicited server were sent using the pre-handshake socket, which
resulted in Z/IP Gateway invalidating the connection and having to
open a new one.

Reply to unsolicited commands on the same DTLS connection

---

lib/grizzly/status_reporter.ex
lib/grizzly/supervisor.ex
lib/grizzly/zipgateway/ready_checker.ex
lib/grizzly/zwave_firmware.ex
test/grizzly/zipgateway/ready_checker_test.exs

This prevents crashes or side-effects in external callbacks from
affecting Grizzly processes (and potentially causing crashes).
In one instance, a `Grizzly.StatusReporter` callback was registering
with a pubsub registery, causing `Grizzly.ZIPGateway.ReadyChecker` to
receive messages that it wasn't expecting.

Execute external callbacks in Tasks

---

lib/grizzly/unsolicited_server.ex

Had `handle_info/2` ever been invoked, it would have raised a lot of
errors due to unhandled response actions (see
`Grizzly.UnsolicitedServer.Socket.run_response_action/3` for
comparison).

Remove dead code from `Grizzly.UnsolicitedServer`

---

lib/grizzly/commands/command.ex
lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/report.ex
test/grizzly/commands/command_runner_test.exs
test/grizzly/commands/command_test.exs

When dealing with timeouts, it was impossible to tell whether the
outgoing command had been acknowledged by the destination node or not.
This adds an `acknowledged` flag to `Grizzly.Report` to indicate such.
This is important in determining the reason for a timeout and whether
failed command should be retried.

Reports indicate command acknowledgement

---

lib/grizzly/commands/table.ex
lib/grizzly/zwave/command_classes/network_management_installation_maintenance.ex
lib/grizzly/zwave/commands/priority_route_set.ex
lib/grizzly/zwave/decoder.ex
test/grizzly/zwave/commands/priority_route_report_test.exs

Priority Route Report was trying to parse the speed parameter the same
as the neighbor speed bitmask from Statistics Report. They are not the
same.

Implement Priority Route Set and fix Priority Route Report

---

lib/grizzly/zwave/command_classes/network_management_installation_maintenance.ex

Speed will be 0 when a node does not have a priority route assigned.

Allow zero speed in Priority Route Report

---

lib/grizzly/zwave/commands/zip_packet/header_extensions.ex

There is no reason to send this header extension to Z/IP Gateway even if
it is specified (usually this happens because header extensions were
copied from an incoming Z/IP Packet).

Outgoing Z/IP Packets ignore install and maintenance header extension

---

lib/grizzly/transport_error.ex
lib/grizzly/transports/DTLS.ex
lib/grizzly/unsolicited_server/socket.ex

The content of the message is not helpful for debugging. Replaced with a
debug log for now. Future investigation will require some inspection
with tcpdump.

Suppress DTLS errors for "TLS Alert: unexpected message"

---

lib/grizzly/zipgateway/exit_monitor.ex
lib/grizzly/zipgateway/supervisor.ex

Since these are UDP connections, we have no way of knowing if the other
side has been closed until a keepalive fails.
This doesn't account for the UnsolicitedServer, but it's less of an
issue since it only deals with incoming datagrams. It's still leaking
resources and is something that sould be fixed (but separately).

Close all DTLS connections on Z/IP Gateway exit

---

lib/grizzly/zwave/notifications.ex

Every notification type has a state_idle event with a single
parameter indicating which state variable has returned to idle.

Decode state_idle event params for all notification types

---

lib/grizzly/version_reports.ex
lib/grizzly/zwave/command_classes/multi_command.ex
test/grizzly_test.exs

The controller reports support for command class `multi_cmd` not `multi_command`.

Correct CC name from multi_command  to multi_cmd

---

lib/grizzly/version_reports.ex
test/grizzly_test.exs

It was set to 1 for the extra command classes.

Grizzly supports v3 of Association Group Info CC

---

lib/grizzly/commands/command.ex
lib/grizzly/zwave/commands/zip_packet/header_extensions.ex

The fix in #843 did not work because the header is
`:installation_and_maintenance_report`, not
`:install_and_maintenance_report` (copy/pasted from the typespec, which
was wrong to begin with).

Fix incorrect installation and maintenance header extension name

---

lib/grizzly/connections/supervisor.ex

If `Grizzly.Connections.Supervisor` is not running,
`close_all_connections/0` should be a no-op.

Catch exits when closing all connections

---

lib/grizzly/status_reporter.ex
lib/grizzly/status_reporter/console.ex
lib/grizzly/zipgateway/log_monitor.ex
lib/grizzly/zipgateway/supervisor.ex
test/grizzly/zipgateway/log_monitor_test.exs

Inspecting Z/IP Gateway's logs can tell us when there's a problem with
the Z-Wave SAPI. Changes in SAPI status are now reported via
`Grizzly.StatusReporter`.

Report Serial API status

---

.credo.exs
lib/grizzly/zwave/decoder.ex

When errors are raised while parsing a command, the original binary
will be included in Logger metadata so that it can be reported to error
monitoring service(s).

Record original command binary in Logger metadata

---

lib/grizzly/zwave/command_classes/sensor_binary.ex
lib/grizzly/zwave/commands/thermostat_mode_supported_report.ex
lib/grizzly/zwave/commands/thermostat_setpoint_supported_report.ex
lib/grizzly/zwave/commands/user_code_capabilities_report.ex
lib/grizzly/zwave/encoding.ex
test/grizzly/zwave/commands/thermostat_mode_supported_report_test.exs
test/grizzly/zwave/commands/thermostat_setpoint_supported_report_test.exs
test/grizzly/zwave/commands/user_code_capabilities_report_test.exs

Instead of keyword lists of the form `[{value, boolean}, ...`, params
that use bitmask encoding will be represented as `[value, ...]` (a list
of enabled values). Lists are easier to work with, especially when
encoding into formats that don't support keyword lists / tuples (e.g.
JSON).

Simplify bitmask encoding and decoding

---

lib/grizzly/zwave/commands/user_code_set.ex
test/grizzly/zwave/commands/user_code_set_test.exs

The Z-Wave spec states that the User Code field must be set to
0x00000000 when User ID Status is 0x00 (available).

Fix User Code Set when User ID Status is 0x00

---

lib/grizzly/transport.ex
lib/grizzly/transports/DTLS.ex
lib/grizzly/transports/UDP.ex
lib/grizzly/unsolicited_server/socket.ex
test/support/UDP.ex

Similar to #864, this adds the sending node's id to Logger metadata for
UnsolicitedServer sockets.

UnsolicitedServer includes node id in Logger metadata

---

lib/grizzly/status_reporter.ex
lib/grizzly/zipgateway/log_monitor.ex
lib/grizzly/zipgateway/sapi_monitor.ex
lib/grizzly/zipgateway/supervisor.ex
test/grizzly/zipgateway/log_monitor_test.exs
test/grizzly/zipgateway/sapi_monitor_test.exs

As it turns out, it's somewhat normal for SAPI hiccups to happen
occasionally. This refactors SAPI status monitoring/reporting such that
the unresponsive status is only triggered when X retransmissions occur in
the last Y seconds.

Fix false positives in SAPI status reporting

---

lib/grizzly/zipgateway/supervisor.ex

If a reset function is provided in Grizzly's startup options, reset the
Z-Wave module when Z/IP Gateway exits to try to resolve cases where the
module has locked up.

Hard reset Z-Wave module on Z/IP Gateway exit

---

lib/grizzly/commands/table.ex
lib/grizzly/zwave/command_classes/sensor_multilevel.ex
lib/grizzly/zwave/commands/sensor_multilevel_supported_scale_get.ex
lib/grizzly/zwave/commands/sensor_multilevel_supported_scale_report.ex
lib/grizzly/zwave/decoder.ex
test/grizzly/zwave/commands/sensor_multilevel_supported_scale_get_test.exs
test/grizzly/zwave/commands/sensor_multilevel_supported_scale_report_test.exs
test/grizzly/zwave/commands/sensor_multilevel_supported_sensor_report_test.exs

Added SensorMultilevelSupportedScaleGet and SensorMultilevelSupportedScaleReport
[SRH-1063]
[SRH-1063]: https://smartrent.atlassian.net/browse/SRH-1063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add missing commands to SensorMultilevel CC

---

lib/grizzly/zwave/commands/thermostat_setpoint_report.ex
test/grizzly/zwave/commands/thermostat_setpoint_report_test.exs

A trailing 0 is sent by the Aidoo Airzone which must be ignored to avoid a parameter decoding failure.
[SRH-1012]
[SRH-1012]: https://smartrent.atlassian.net/browse/SRH-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ignore extra trailing bytes when decoding ThermostatSetpointReport

---

lib/grizzly/firmware_updates.ex
lib/grizzly/firmware_updates/firmware_update_runner.ex

Also support stopping a firmware update run
Timeouts were not handled, crashing the firmware update process.
Required by the Piston DeviceFirmwareUpdater.
[SRH-552]
[SRH-552]: https://smartrent.atlassian.net/browse/SRH-552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Handling command timeouts and queueing when updating firmware

---

lib/grizzly/commands/command_runner.ex

Stopping an already-stopped CommandRunner shouldn't be an error.

Catch exit when stopping dead CommandRunner

---

lib/grizzly/zwave/commands/battery_report.ex
test/grizzly/zwave/commands/battery_report_test.exs

Some door locks can sometimes report a battery level > 100. Allow any
value in Battery Reports and clamp to 0..100.

Allow any value when decoding battery level

---

lib/grizzly/zwave/commands/door_lock_operation_report.ex

Added to support a lock that only sends 4 bytes.

Allow 4 byte input for Door Lock Operation Report

---

.circleci/config.yml

Changed all instances of 3.18.4 to 3.18.6. I'm not sure if my changes deal with all of the vulnerabilities. When I changed 3.18.4 to 3.18.6 it errored and said that version didn't exist.

Update Alpine Version in CircleCI Config

---

lib/grizzly/zwave/commands/included_nif_report.ex
lib/grizzly/zwave/decoder.ex
lib/grizzly/zwave/dsk.ex

Implements the Included NIF Report command from the Network Management
Inclusion CC. This command is received when a node that is on the
provisioning list sends a SmartStart INIF but has another network's home
id.

Implement Included NIF Report command

---

lib/grizzly/commands/command.ex
lib/grizzly/firmware_updates.ex
lib/grizzly/firmware_updates/firmware_update_runner.ex
lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex

When starting a firmware update for a wakeup device, the firmware update
won't be considered as started until the device has requested at least
one image fragment. This allows users to enqueue a firmware update
request without blocking communication with other devices.
Additionally, all firmware update commands are now sent with the more
info flag set in the Z/IP Packet.

Improve firmware updates for wakeup devices

---

lib/grizzly.ex
lib/grizzly/commands/command.ex
lib/grizzly/connection.ex
lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/supervisor.ex
lib/grizzly/firmware_updates/firmware_update_runner.ex
lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
lib/grizzly/node_id.ex
lib/grizzly/switch_binary.ex

`AsyncConnection` is a bit of a misnomer. While it does only support
sending commands asynchronously, the defining feature (and a critical
point that was never documented) is that an `AsyncConnection` is meant
to be owned and used by a single process (thus its use in inclusion and
firmware upgrades). A clearer name would be `OwnedConnection`.
The upshot of this behavior is that if two different processes were to
send a command with `mode: :async`, the first process to do so would
receive all of the status messages and the second process would get
nothing.
This adds an option to `AsyncConnection.start_link/3` to start an
unnamed connection rather than potentially reusing an existing named
connection.

Allow creation of unnamed `AsyncConnection`s

---

lib/grizzly/zwave/command_classes/user_code.ex

Some door locks support non-standard user id statuses. To support that,
Grizzly will continue to translate known values into atoms, but values
not defined in the spec will be passed through as integers.

Allow undefined values for user id status

---

lib/grizzly/commands/command.ex
lib/grizzly/commands/command_runner.ex
lib/grizzly/connection.ex
lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/report.ex
test/grizzly/commands/command_runner_test.exs
test/grizzly/commands/command_test.exs
test/grizzly/connections/command_list_test.exs
test/grizzly/connections/sync_connection_test.exs
test/grizzly_test.exs
test/support/server.ex

When a queued command resolves to a nack response, we were previously
sending `{:error, :nack_response}` back to the calling process. This is
lacking vital information (specifically, the command ref) that a caller
needs to know which queued command failed, especially if the caller has
queued multiple commands.
Instead, we will now send `{:grizzly, :report, %Grizzly.Report{}}` as we
do for other types of responses. The report will have a status of
`:complete` and a type of `:nack_response`.

Send a Grizzly.Report for nack responses to queued commands

---

lib/grizzly/firmware_updates/firmware_update_runner.ex

Log at debug level instead of warning or info when ignoring a firmware update-related report or response

Quiet down logs when ignoring fw update reports

---

lib/grizzly/zipgateway/supervisor.ex

Turns out muontrap doesn't add the ": " for you when using a custom log
prefix.

Fix Z/IP Gateway log prefix

---

lib/grizzly/unsolicited_server/socket.ex

Setting more info in an ack response doesn't do anything. The flag is
only respected for requests (and only requests that go through Z/IP
Gateway's mailbox).

Remove more info flag from ack responses

---

lib/grizzly/options.ex
lib/grizzly/supervisor.ex
lib/grizzly/zipgateway/config.ex
lib/grizzly/zipgateway/supervisor.ex
priv/zipgateway.cfg
test/grizzly/zipgateway/config_test.exs

The old EEPROM file storage has been unsupported in Z/IP Gateway for a
few years now. Just including the `EepromFile` config item in the ZGW
config file will cause a fatal error at startup.

Remove support for Z/IP Gateway EEPROM migration

---

lib/grizzly/zwave/commands/node_provisioning_set.ex
test/grizzly/zwave/commands/node_provisioning_set_test.exs

Failing to handle the `dsk` param being a binary or a
`Grizzly.ZWave.DSK` struct causes errors in `Grizzly.Trace`.

Fix encoding of Node Provisioning Set command

---

.formatter.exs
lib/grizzly/connections/async_connection.ex
lib/grizzly/firmware_updates.ex
lib/grizzly/firmware_updates/firmware_update_runner.ex
lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
test/grizzly/firmware_updates/firmware_update_runner/firmware_update_test.exs
test/grizzly/firmware_updates/firmware_update_runner_test.exs
test/support/UDP.ex
test/support/server.ex
test/test_helper.exs

Firmware updates now dynamically adjust the delay between transmitting
fragments based on the active transmission speed (10ms for 100kbps and
35ms otherwise, as defined by the spec).
It is also possible to override the transmission delay in case rapid
transmissions cause issues for a particular device.
Additionally, any commands that fail during a firmware update will be
retried up to 2 times in case of nack responses due to transmission
bursts.

Firmware update dynamic transmission delays

---

lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
test/grizzly/firmware_updates/firmware_update_runner/firmware_update_test.exs

After reviewing the spec, I'm not sure where 10ms originally came from.

Firmware update transmission delay is 15ms at 100kbps

---

lib/grizzly.ex
lib/grizzly/commands/table.ex
lib/grizzly/connection.ex
lib/grizzly/virtual_devices.ex
lib/grizzly/virtual_devices/reports.ex
lib/grizzly/virtual_devices/virtual_devices_registry.ex
lib/grizzly/zwave/commands/sensor_multilevel_supported_scale_report.ex
mix.exs

Shuffled a couple of typespecs around to avoid referencing private
modules.

Fix warnings when building docs

---

lib/grizzly/connections/async_connection.ex
lib/grizzly/connections/binary_connection.ex
lib/grizzly/connections/sync_connection.ex
lib/grizzly/trace.ex
lib/grizzly/trace/record.ex
lib/grizzly/transport.ex
lib/grizzly/transports/DTLS.ex
lib/grizzly/unsolicited_server/socket.ex
test/grizzly/trace/record_test.exs
test/grizzly/trace_test.exs
test/grizzly/transports/dtls_test.exs
test/support/UDP.ex

Having IPv6 addresses in traces is really annoying when all you care
about is the node id.

Traces record node ids instead of IP addresses

---

lib/grizzly/command_handlers/supervision_report.ex
lib/grizzly/commands/command.ex
test/grizzly/commands/command_runner_test.exs
test/grizzly/commands/command_test.exs
test/grizzly/connections/command_list_test.exs

The acknowledged flag from the `Grizzly.Commands.Command` was not always
being copied into `Grizzly.Report` correctly.

Fix acknowledged flag sometimes being incorrectly false

---

lib/grizzly/zwave/commands/alarm_event_supported_report.ex
lib/grizzly/zwave/commands/alarm_type_supported_report.ex
lib/grizzly/zwave/notifications.ex

Added new notifications from the 2024A spec and made some corrections
to existing notifications.
Also refactored `Grizzly.ZWave.Notifications` to use lookup tables
instead of macros.

Add missing notifications and reduce macro usage

---

.gitattributes
docs/cookbook.md
lib/grizzly/zwave/command_classes/zwaveplus_info.ex
lib/grizzly/zwave/commands/version_report.ex
lib/grizzly/zwave/device_class.ex
lib/grizzly/zwave/device_classes.ex
lib/grizzly/zwave/generated_mappings.ex
lib/grizzly/zwave/icon_type.ex
lib/mix/tasks/zwave.gen.xml_mappings.ex
resources/ZWave_custom_cmd_classes.xml
test/grizzly/virtual_devices_test.exs
test/grizzly/zwave/commands/node_add_status_test.exs

In support of this, update all usages of the term "slave" with "end
node".

Update Z-Wave XML to 2024A specification

---

lib/grizzly/zwave/command_classes.ex
test/grizzly/zwave/command_classes_test.exs

Ignore extended CCs when parsing command class lists

---

lib/grizzly/zwave/commands/multi_channel_endpoint_find.ex
test/grizzly/zwave/commands/multi_channel_endpoint_find_test.exs

The special case device classes of `:all` and `:all` will return all
endpoints regardless of device class.

Support finding all endpoints with Multi Channel Endpoint Find

---

lib/grizzly/inclusion_server.ex
lib/grizzly/inclusions.ex
lib/grizzly/supervisor.ex
lib/grizzly/unsolicited_server/response_handler.ex

When an inclusion controller adds a new node, Z/IP Gateway will inform
us via the unsolicited destination. The rest of the inclusion process
remains the same.
In order for this to work, the `:inclusion_handler` option must be set
when starting `Grizzly.Supervisor`. Additionally, Z/IP Gateway must be
modified so that it doesn't compare port numbers for network management
commands. Perhaps one day, we'll do some refactoring to make it work the
"right way" (i.e. sending the inclusion commands back via the
unsolicited server connection).
SRH-1572

Continue inclusion started by an inclusion controller

---

lib/grizzly/zwave/dsk.ex
test/grizzly/zwave/dsk_test.exs

The NWI Home ID is the Home ID used by a SmartStart node when it is not
yet included in a network. It is defined as bytes 9-12 of the DSK with
the two most significant bits set and the least significant bit cleared.

Add util to get NWI home id from DSK

---

lib/grizzly/zwave/commands/sensor_multilevel_get.ex
test/grizzly/zwave/commands/sensor_multilevel_get_test.exs

Aligns with the changes to Sensor Multilevel Report in #995.

Use atoms for scale in Sensor Multilevel Get

---

lib/grizzly/zwave/commands/alarm_report.ex
lib/grizzly/zwave/notifications.ex
test/grizzly/zwave/commands/alarm_report_test.exs

Allow for alarm types and events to be undecodable
[SRH-1583]
[SRH-1583]: https://smartrent.atlassian.net/browse/SRH-1583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Support alarm reports for Alarm CC v1

---

lib/grizzly/zwave/commands/alarm_type_supported_report.ex
test/grizzly/zwave/commands/alarm_type_supported_report_test.exs

Decoding of :alarm_type_supported_type_report fails for devices also implementing v1 of alarm types
The alarm_v1 flag can be 0 or 1. The current implementation  expects only 0.
```
0 = the device implements only Notification CC V2 (or newer) Notification Type(s).
1 = the device implements Notification CC V2 Notification Types as well as proprietary Alarm CC V1 Alarm Types and Alarm Levels.
```

Handle alarm v1 support flag not 0 in alarm_type_supported_report

---

lib/grizzly.ex
lib/grizzly/associations.ex
lib/grizzly/network.ex
lib/grizzly/unsolicited_server/response_handler.ex
lib/grizzly/zwave.ex
test/grizzly/associations_test.exs
test/grizzly/unsolicited_server/response_handler_test.exs

We weren't properly handling Multi Channel Association Set for endpoint
associations. This fixes a couple of certification test cases.

Properly handle multi channel association commands

---

lib/grizzly/network.ex

The timeout was set at 10s which could cause timeouts. It is now set to 60s.
[SRH-1792]
[SRH-1792]: https://smartrent.atlassian.net/browse/SRH-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow more time for the default_set (zwave reset) command to complete

---

lib/grizzly/zwave/command_classes/switch_support.ex
lib/grizzly/zwave/commands/switch_binary_report.ex
lib/grizzly/zwave/commands/switch_binary_set.ex
lib/grizzly/zwave/commands/switch_multilevel_report.ex
lib/grizzly/zwave/commands/switch_multilevel_set.ex
test/grizzly/zwave/commands/switch_binary_report_test.exs
test/grizzly/zwave/commands/switch_multilevel_report_test.exs
test/grizzly/zwave/commands/switch_multilevel_set_test.exs

Whether a binary or multilevel switch,
instead of passing the duration pre-encoded.
Required for certification
[SRH-1797]
[SRH-1797]: https://smartrent.atlassian.net/browse/SRH-1797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use seconds or :default to give the duration when setting a switch

---

lib/grizzly/zwave/command_classes/humidity_control_setpoint.ex
test/grizzly/zwave/commands/humidity_control_setpoint_capabilities_get_test.exs
test/grizzly/zwave/commands/humidity_control_setpoint_capabilities_report_test.exs
test/grizzly/zwave/commands/humidity_control_setpoint_get_test.exs
test/grizzly/zwave/commands/humidity_control_setpoint_report_test.exs
test/grizzly/zwave/commands/humidity_control_setpoint_scale_supported_get_test.exs
test/grizzly/zwave/commands/humidity_control_setpoint_set_test.exs
test/grizzly/zwave/commands/humidity_control_setpoint_supported_report_test.exs

Renamed `:humidifier` and `:dehumidifier` to `:humidify` and
`:dehumidify` to align with the humidity control mode names.

Rename humidity control setpoint types

---

lib/grizzly/firmware_updates/firmware_update_runner.ex
lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex
test/grizzly/firmware_updates/firmware_update_runner/firmware_update_test.exs

The inter-fragment delays only apply when sending multiple fragments per
batch. If the device only requests one fragment at a time, no delay is
needed.

Disable inter-fragment delay when only one fragment is requested

---

test/grizzly/command_handlers/wait_report_test.exs
test/support/server/handler.ex

The test tries to send two commands out of order, but sometimes due to
the two async processes not being coordinated, the commands sometimes
end up going out in order. However, the mock Z/IP Gateway server always
sends the responses out of order, so we just need to make sure that the
data is matched up correctly.

Fix flaky WaitReport handler test

---

lib/grizzly/background_rssi_monitor.ex
lib/grizzly/firmware_updates.ex
lib/grizzly/firmware_updates/firmware_update_runner.ex
lib/grizzly/firmware_updates/firmware_update_runner/firmware_update.ex

It's been observed that sometimes Z/IP Gateway doesn't end up sending
an ack or nack response to a packet when an S2 nonce exchange fails.
This can happen in environments with a lot of background noise. When
this happened, Grizzly would immediately abort the firmware update
without retrying anything, oftentimes prematurely. This could happen
even if the target device had resumed the update by sending a new
Firmware Update Metadata Get command.
Additionally, Grizzly would ignore nack responses and wait for the next
Firmware Update Metadata Get from the target device to resume sending
fragments. This could cause the firmware update to stall due to
transient noise events (such as a nearby wakeup beam).
In both cases, we will now retry the last transmitted command up to 10
times in an attempt …

Improve error handling during firmware updates
